include_guard(GLOBAL)

set(_H747_MEM_RAM_D1_BASE 0x24000000)
set(_H747_MEM_RAM_D1_SIZE 0x00080000)
set(_H747_MEM_FLASH_BASE 0x08000000)
set(_H747_MEM_FLASH_SIZE 0x00200000)
set(_H747_MEM_RAM_D2_BASE 0x30000000)
set(_H747_MEM_RAM_D2_SIZE 0x00048000)
set(_H747_MEM_SDRAM_BASE 0xD0000000)
set(_H747_MEM_SDRAM_SIZE 0x01000000)

function(_h747_mem_hex out_var value)
    math(EXPR _hex_value "${value}" OUTPUT_FORMAT HEXADECIMAL)
    string(TOUPPER "${_hex_value}" _hex_value)
    string(REPLACE "0X" "0x" _hex_value "${_hex_value}")
    set(${out_var} "${_hex_value}" PARENT_SCOPE)
endfunction()

function(_h747_mem_region out_var address)
    math(EXPR _ram_d1_end "${_H747_MEM_RAM_D1_BASE} + ${_H747_MEM_RAM_D1_SIZE}")
    math(EXPR _flash_end "${_H747_MEM_FLASH_BASE} + ${_H747_MEM_FLASH_SIZE}")
    math(EXPR _ram_d2_end "${_H747_MEM_RAM_D2_BASE} + ${_H747_MEM_RAM_D2_SIZE}")
    math(EXPR _sdram_end "${_H747_MEM_SDRAM_BASE} + ${_H747_MEM_SDRAM_SIZE}")

    if(address GREATER_EQUAL _H747_MEM_RAM_D1_BASE AND address LESS _ram_d1_end)
        set(${out_var} "RAM_D1" PARENT_SCOPE)
    elseif(address GREATER_EQUAL _H747_MEM_FLASH_BASE AND address LESS _flash_end)
        set(${out_var} "FLASH" PARENT_SCOPE)
    elseif(address GREATER_EQUAL _H747_MEM_RAM_D2_BASE AND address LESS _ram_d2_end)
        set(${out_var} "RAM_D2" PARENT_SCOPE)
    elseif(address GREATER_EQUAL _H747_MEM_SDRAM_BASE AND address LESS _sdram_end)
        set(${out_var} "SDRAM" PARENT_SCOPE)
    else()
        set(${out_var} "OTHER" PARENT_SCOPE)
    endif()
endfunction()

function(_h747_mem_section_for_addr out_section out_region sections address)
    set(_found_section "UNKNOWN")
    set(_found_region "OTHER")
    foreach(_section_record IN LISTS ${sections})
        string(REPLACE "|" ";" _section_fields "${_section_record}")
        list(GET _section_fields 0 _section_name)
        list(GET _section_fields 1 _section_addr)
        list(GET _section_fields 2 _section_size)
        list(GET _section_fields 3 _section_region)
        math(EXPR _section_end "${_section_addr} + ${_section_size}")
        if(address GREATER_EQUAL _section_addr AND address LESS _section_end)
            set(_found_section "${_section_name}")
            set(_found_region "${_section_region}")
            break()
        endif()
    endforeach()
    set(${out_section} "${_found_section}" PARENT_SCOPE)
    set(${out_region} "${_found_region}" PARENT_SCOPE)
endfunction()

function(_h747_mem_append_top_symbols out_text title records top_n)
    set(_lines "\n[${title}]\n")
    set(_items ${${records}})
    list(REVERSE _items)
    set(_count 0)
    foreach(_record IN LISTS _items)
        if(_count GREATER_EQUAL top_n)
            break()
        endif()
        string(REPLACE "|" ";" _fields "${_record}")
        list(GET _fields 0 _size)
        list(GET _fields 1 _addr)
        list(GET _fields 2 _type)
        list(GET _fields 3 _section)
        list(GET _fields 4 _name)
        _h747_mem_hex(_addr_hex "${_addr}")
        string(APPEND _lines "${_addr_hex} size=${_size} type=${_type} section=${_section} name=${_name}\n")
        math(EXPR _count "${_count} + 1")
    endforeach()
    set(${out_text} "${_lines}" PARENT_SCOPE)
endfunction()

function(_h747_mem_fail message_text)
    message(FATAL_ERROR "h747_lab_player_md3 memory gate: ${message_text}")
endfunction()

function(_h747_mem_run_evidence)
    if(NOT H747_MEMORY_ELF OR NOT EXISTS "${H747_MEMORY_ELF}")
        _h747_mem_fail("missing ELF '${H747_MEMORY_ELF}'")
    endif()
    if(NOT H747_MEMORY_OUT)
        _h747_mem_fail("missing H747_MEMORY_OUT")
    endif()
    if(NOT H747_MEMORY_SIZE_TOOL OR NOT EXISTS "${H747_MEMORY_SIZE_TOOL}")
        _h747_mem_fail("missing size tool '${H747_MEMORY_SIZE_TOOL}'")
    endif()
    if(NOT H747_MEMORY_NM_TOOL OR NOT EXISTS "${H747_MEMORY_NM_TOOL}")
        _h747_mem_fail("missing nm tool '${H747_MEMORY_NM_TOOL}'")
    endif()
    if(NOT H747_MEMORY_TOP_N)
        set(H747_MEMORY_TOP_N 32)
    endif()
    if(NOT DEFINED H747_MEMORY_GATE)
        set(H747_MEMORY_GATE ON)
    endif()
    if(NOT DEFINED H747_MEMORY_RAM_D1_RECORD_BYTES OR H747_MEMORY_RAM_D1_RECORD_BYTES STREQUAL "")
        set(H747_MEMORY_RAM_D1_RECORD_BYTES 0)
    endif()

    execute_process(
        COMMAND "${H747_MEMORY_SIZE_TOOL}" -A "${H747_MEMORY_ELF}"
        RESULT_VARIABLE _size_result
        OUTPUT_VARIABLE _size_output
        ERROR_VARIABLE _size_error)
    if(NOT _size_result EQUAL 0)
        _h747_mem_fail("size -A failed: ${_size_error}")
    endif()

    execute_process(
        COMMAND "${H747_MEMORY_NM_TOOL}" -S --size-sort -C "${H747_MEMORY_ELF}"
        RESULT_VARIABLE _nm_result
        OUTPUT_VARIABLE _nm_output
        ERROR_VARIABLE _nm_error)
    if(NOT _nm_result EQUAL 0)
        _h747_mem_fail("nm failed: ${_nm_error}")
    endif()

    execute_process(
        COMMAND "${H747_MEMORY_NM_TOOL}" -C "${H747_MEMORY_ELF}"
        RESULT_VARIABLE _nm_abs_result
        OUTPUT_VARIABLE _nm_abs_output
        ERROR_VARIABLE _nm_abs_error)
    if(NOT _nm_abs_result EQUAL 0)
        _h747_mem_fail("nm absolute-symbol scan failed: ${_nm_abs_error}")
    endif()

    set(_controller_profile_fields
        controller_size_bytes
        track_capacity
        library_row_model_size_bytes
        list_order_bytes
        list_rows_bytes
        duration_cache_bytes
        list_cover_paths_bytes
        list_cover_cache_capacity
        list_cover_cache_bytes
        current_cover_bytes
        cover_theme_bytes
        now_playing_roles_bytes
        text_state_bytes
        cover_path_state_bytes
        font_path_state_bytes
        weekly_stats_bytes
        weekly_history_bytes
        ui_handles_bytes
        icon_ids_bytes
        playback_engine_bytes)
    foreach(_field IN LISTS _controller_profile_fields)
        set("_controller_profile_${_field}" "MISSING")
    endforeach()
    set(_style_sheet_profile_fields
        widget_kind_count
        total_style_slots
        total_variant_slots
        max_metrics_pool
        style_rule_capacity
        resolved_colors_bytes
        resolved_decoration_bytes
        resolved_metrics_pool_bytes
        metrics_id_bytes
        matched_bytes
        kind_compiled_bytes
        style_table_static_bytes
        base_style_bytes
        base_style_set_bytes
        rule_storage_bytes
        stylesheet_size_bytes)
    foreach(_field IN LISTS _style_sheet_profile_fields)
        set("_style_sheet_profile_${_field}" "MISSING")
    endforeach()

    set(_sections)
    set(_ram_d1_used 0)
    set(_ram_d2_used 0)
    set(_sdram_used 0)
    set(_flash_vma_used 0)
    set(_icon_buf_ram_d1_count 0)
    set(_icon_buf_ram_d1_bytes 0)
    set(_profile_player_controller_size 0)
    set(_profile_player_controller_region "UNKNOWN")
    set(_profile_player_controller_section "UNKNOWN")
    set(_profile_theme_size 0)
    set(_profile_theme_region "UNKNOWN")
    set(_profile_theme_section "UNKNOWN")
    set(_profile_style_sheet_size 0)
    set(_profile_style_sheet_region "UNKNOWN")
    set(_profile_style_sheet_section "UNKNOWN")
    set(_profile_image_registry_size 0)
    set(_profile_image_registry_region "UNKNOWN")
    set(_profile_image_registry_section "UNKNOWN")
    set(_profile_fatfs_size 0)
    set(_profile_fatfs_region "UNKNOWN")
    set(_profile_fatfs_section "UNKNOWN")
    set(_profile_style_slot_count 0)
    set(_profile_style_slot_bytes 0)
    string(REPLACE "\r\n" "\n" _size_output "${_size_output}")
    string(REPLACE "\n" ";" _size_lines "${_size_output}")
    foreach(_line IN LISTS _size_lines)
        if(_line MATCHES "^([^ \t]+)[ \t]+([0-9]+)[ \t]+([0-9]+)")
            set(_section_name "${CMAKE_MATCH_1}")
            set(_section_size "${CMAKE_MATCH_2}")
            set(_section_addr "${CMAKE_MATCH_3}")
            if(_section_size EQUAL 0)
                continue()
            endif()
            _h747_mem_region(_section_region "${_section_addr}")
            list(APPEND _sections "${_section_name}|${_section_addr}|${_section_size}|${_section_region}")
            if(_section_region STREQUAL "RAM_D1")
                math(EXPR _ram_d1_used "${_ram_d1_used} + ${_section_size}")
            elseif(_section_region STREQUAL "RAM_D2")
                math(EXPR _ram_d2_used "${_ram_d2_used} + ${_section_size}")
            elseif(_section_region STREQUAL "SDRAM")
                math(EXPR _sdram_used "${_sdram_used} + ${_section_size}")
            elseif(_section_region STREQUAL "FLASH")
                math(EXPR _flash_vma_used "${_flash_vma_used} + ${_section_size}")
            endif()

            math(EXPR _section_end "${_section_addr} + ${_section_size}")
            _h747_mem_region(_section_end_region "${_section_end} - 1")
            if(NOT _section_region STREQUAL _section_end_region)
                _h747_mem_fail("section ${_section_name} crosses memory region boundary")
            endif()
            if(_section_name STREQUAL ".data" OR _section_name STREQUAL ".bss" OR _section_name STREQUAL "._user_heap_stack")
                if(H747_MEMORY_GATE AND NOT _section_region STREQUAL "RAM_D1")
                    _h747_mem_fail("section ${_section_name} must stay in RAM_D1, got ${_section_region}")
                endif()
            endif()
            if(_section_name STREQUAL ".dma_buffer")
                if(H747_MEMORY_GATE AND NOT _section_region STREQUAL "RAM_D2")
                    _h747_mem_fail("section .dma_buffer must stay in RAM_D2, got ${_section_region}")
                endif()
            endif()
            if(_section_name STREQUAL ".sdram")
                if(H747_MEMORY_GATE AND NOT _section_region STREQUAL "SDRAM")
                    _h747_mem_fail("section .sdram must stay in SDRAM, got ${_section_region}")
                endif()
            endif()
        endif()
    endforeach()

    set(_ram_d1_symbols)
    set(_ram_d2_symbols)
    set(_sdram_symbols)
    set(_key_symbols)
    set(_rx_dma_region "MISSING")
    set(_rx_dma_section "MISSING")
    string(REPLACE "\r\n" "\n" _nm_output "${_nm_output}")
    string(REPLACE "\n" ";" _nm_lines "${_nm_output}")
    foreach(_line IN LISTS _nm_lines)
        if(NOT _line MATCHES "^([0-9A-Fa-f]+)[ \t]+([0-9A-Fa-f]+)[ \t]+([^ \t])[ \t]+(.+)$")
            continue()
        endif()
        math(EXPR _symbol_addr "0x${CMAKE_MATCH_1}")
        math(EXPR _symbol_size "0x${CMAKE_MATCH_2}")
        set(_symbol_type "${CMAKE_MATCH_3}")
        set(_symbol_name "${CMAKE_MATCH_4}")
        if(_symbol_size EQUAL 0)
            continue()
        endif()

        _h747_mem_section_for_addr(_symbol_section _symbol_region _sections "${_symbol_addr}")
        if(_symbol_region STREQUAL "RAM_D1")
            list(APPEND _ram_d1_symbols "${_symbol_size}|${_symbol_addr}|${_symbol_type}|${_symbol_section}|${_symbol_name}")
        elseif(_symbol_region STREQUAL "RAM_D2")
            list(APPEND _ram_d2_symbols "${_symbol_size}|${_symbol_addr}|${_symbol_type}|${_symbol_section}|${_symbol_name}")
        elseif(_symbol_region STREQUAL "SDRAM")
            list(APPEND _sdram_symbols "${_symbol_size}|${_symbol_addr}|${_symbol_type}|${_symbol_section}|${_symbol_name}")
        endif()

        set(_is_key FALSE)
        set(_forbid_sdram FALSE)
        if(_symbol_name MATCHES "g_rx_dma_buffer")
            set(_is_key TRUE)
            set(_rx_dma_region "${_symbol_region}")
            set(_rx_dma_section "${_symbol_section}")
        elseif(_symbol_name MATCHES "controller_ref\\(\\)::controller")
            set(_is_key TRUE)
            set(_forbid_sdram TRUE)
            set(_profile_player_controller_size "${_symbol_size}")
            set(_profile_player_controller_region "${_symbol_region}")
            set(_profile_player_controller_section "${_symbol_section}")
        elseif(_symbol_name MATCHES "StyleSheet.*instance\\(\\)::inst")
            set(_is_key TRUE)
            set(_forbid_sdram TRUE)
            set(_profile_style_sheet_size "${_symbol_size}")
            set(_profile_style_sheet_region "${_symbol_region}")
            set(_profile_style_sheet_section "${_symbol_section}")
        elseif(_symbol_name MATCHES "Theme.*instance\\(\\)::inst")
            set(_is_key TRUE)
            set(_forbid_sdram TRUE)
            set(_profile_theme_size "${_symbol_size}")
            set(_profile_theme_region "${_symbol_region}")
            set(_profile_theme_section "${_symbol_section}")
        elseif(_symbol_name MATCHES "image_registry.*\\(\\)::registry")
            set(_is_key TRUE)
            set(_profile_image_registry_size "${_symbol_size}")
            set(_profile_image_registry_region "${_symbol_region}")
            set(_profile_image_registry_section "${_symbol_section}")
        elseif(_symbol_name MATCHES "mount_fatfs_from_sd.*::fat")
            set(_is_key TRUE)
            set(_profile_fatfs_size "${_symbol_size}")
            set(_profile_fatfs_region "${_symbol_region}")
            set(_profile_fatfs_section "${_symbol_section}")
        elseif(_symbol_name MATCHES "PlayerMd3State")
            set(_is_key TRUE)
        elseif(_symbol_name MATCHES "SoaKernel|soa")
            set(_forbid_sdram TRUE)
        endif()

        if(_symbol_name MATCHES "style_slot@.*::value")
            math(EXPR _profile_style_slot_count "${_profile_style_slot_count} + 1")
            math(EXPR _profile_style_slot_bytes "${_profile_style_slot_bytes} + ${_symbol_size}")
        endif()
        if(_symbol_name MATCHES "player::ui::icon_.*\\(\\)::buf" AND _symbol_region STREQUAL "RAM_D1")
            math(EXPR _icon_buf_ram_d1_count "${_icon_buf_ram_d1_count} + 1")
            math(EXPR _icon_buf_ram_d1_bytes "${_icon_buf_ram_d1_bytes} + ${_symbol_size}")
            if(H747_MEMORY_GATE)
                _h747_mem_fail("Player icon buffer '${_symbol_name}' must use the SDRAM icon arena, not RAM_D1")
            endif()
        endif()
        if(H747_MEMORY_GATE AND _forbid_sdram AND _symbol_region STREQUAL "SDRAM")
            _h747_mem_fail("core runtime symbol '${_symbol_name}' must not be placed in SDRAM")
        endif()
        if(_is_key)
            list(APPEND _key_symbols "${_symbol_size}|${_symbol_addr}|${_symbol_type}|${_symbol_region}|${_symbol_section}|${_symbol_name}")
        endif()
    endforeach()

    string(REPLACE "\r\n" "\n" _nm_abs_output "${_nm_abs_output}")
    string(REPLACE "\n" ";" _nm_abs_lines "${_nm_abs_output}")
    foreach(_line IN LISTS _nm_abs_lines)
        if(_line MATCHES "^([0-9A-Fa-f]+)[ \t]+A[ \t]+charm_player_controller_profile_([A-Za-z0-9_]+)$")
            math(EXPR _profile_value "0x${CMAKE_MATCH_1}")
            set("_controller_profile_${CMAKE_MATCH_2}" "${_profile_value}")
        elseif(_line MATCHES "^([0-9A-Fa-f]+)[ \t]+A[ \t]+charm_style_sheet_profile_([A-Za-z0-9_]+)$")
            math(EXPR _profile_value "0x${CMAKE_MATCH_1}")
            set("_style_sheet_profile_${CMAKE_MATCH_2}" "${_profile_value}")
        endif()
    endforeach()

    if(H747_MEMORY_GATE)
        if(NOT _rx_dma_region STREQUAL "RAM_D2")
            _h747_mem_fail("g_rx_dma_buffer must be in RAM_D2, got ${_rx_dma_region}")
        endif()
        if(NOT _rx_dma_section STREQUAL ".dma_buffer")
            _h747_mem_fail("g_rx_dma_buffer must be in .dma_buffer, got ${_rx_dma_section}")
        endif()
        if(_profile_player_controller_size EQUAL 0)
            _h747_mem_fail("missing PlayerController size evidence")
        endif()
        if(_profile_theme_size EQUAL 0)
            _h747_mem_fail("missing Theme size evidence")
        endif()
        if(_profile_style_sheet_size EQUAL 0)
            _h747_mem_fail("missing StyleSheet size evidence")
        endif()
        if(_controller_profile_controller_size_bytes STREQUAL "MISSING")
            _h747_mem_fail("missing PlayerController fixed-capacity profile symbols")
        endif()
        if(NOT _controller_profile_controller_size_bytes EQUAL _profile_player_controller_size)
            _h747_mem_fail("PlayerController profile size ${_controller_profile_controller_size_bytes} does not match symbol size ${_profile_player_controller_size}")
        endif()
        if(_style_sheet_profile_stylesheet_size_bytes STREQUAL "MISSING")
            _h747_mem_fail("missing StyleSheet static-capacity profile symbols")
        endif()
        if(NOT _style_sheet_profile_stylesheet_size_bytes EQUAL _profile_style_sheet_size)
            _h747_mem_fail("StyleSheet profile size ${_style_sheet_profile_stylesheet_size_bytes} does not match symbol size ${_profile_style_sheet_size}")
        endif()
    endif()

    set(_flash_bin_bytes 0)
    if(H747_MEMORY_BIN AND EXISTS "${H747_MEMORY_BIN}")
        file(SIZE "${H747_MEMORY_BIN}" _flash_bin_bytes)
    endif()
    math(EXPR _ram_d1_record_delta "${_ram_d1_used} - ${H747_MEMORY_RAM_D1_RECORD_BYTES}")

    get_filename_component(_memory_out_dir "${H747_MEMORY_OUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${_memory_out_dir}")
    set(_out_text "# Generated H747 Player MD3 memory evidence.\n")
    string(APPEND _out_text "target=${H747_MEMORY_TARGET}\n")
    string(APPEND _out_text "elf=${H747_MEMORY_ELF}\n")
    string(APPEND _out_text "bin=${H747_MEMORY_BIN}\n")
    string(APPEND _out_text "gate=${H747_MEMORY_GATE}\n")
    string(APPEND _out_text "top_n=${H747_MEMORY_TOP_N}\n")
    string(APPEND _out_text "\n[memory]\n")
    string(APPEND _out_text "RAM_D1.used_bytes=${_ram_d1_used}\n")
    string(APPEND _out_text "RAM_D1.size_bytes=524288\n")
    string(APPEND _out_text "RAM_D1.record_threshold_bytes=${H747_MEMORY_RAM_D1_RECORD_BYTES}\n")
    string(APPEND _out_text "RAM_D1.record_delta_bytes=${_ram_d1_record_delta}\n")
    string(APPEND _out_text "RAM_D1.record_gate=record_only\n")
    string(APPEND _out_text "RAM_D2.used_bytes=${_ram_d2_used}\n")
    string(APPEND _out_text "RAM_D2.size_bytes=294912\n")
    string(APPEND _out_text "SDRAM.used_bytes=${_sdram_used}\n")
    string(APPEND _out_text "SDRAM.size_bytes=16777216\n")
    string(APPEND _out_text "FLASH.bin_bytes=${_flash_bin_bytes}\n")
    string(APPEND _out_text "FLASH.vma_section_bytes=${_flash_vma_used}\n")
    string(APPEND _out_text "PLAYER_ICON.ram_d1_buffer_count=${_icon_buf_ram_d1_count}\n")
    string(APPEND _out_text "PLAYER_ICON.ram_d1_buffer_bytes=${_icon_buf_ram_d1_bytes}\n")
    string(APPEND _out_text "PLAYER_ICON.expected_arena_bytes=156672\n")

    string(APPEND _out_text "\n[player_runtime_profile]\n")
    string(APPEND _out_text "PlayerController.size_bytes=${_profile_player_controller_size}\n")
    string(APPEND _out_text "PlayerController.region=${_profile_player_controller_region}\n")
    string(APPEND _out_text "PlayerController.section=${_profile_player_controller_section}\n")
    string(APPEND _out_text "Theme.size_bytes=${_profile_theme_size}\n")
    string(APPEND _out_text "Theme.region=${_profile_theme_region}\n")
    string(APPEND _out_text "Theme.section=${_profile_theme_section}\n")
    string(APPEND _out_text "StyleSheet.size_bytes=${_profile_style_sheet_size}\n")
    string(APPEND _out_text "StyleSheet.region=${_profile_style_sheet_region}\n")
    string(APPEND _out_text "StyleSheet.section=${_profile_style_sheet_section}\n")
    string(APPEND _out_text "ImageRegistry.size_bytes=${_profile_image_registry_size}\n")
    string(APPEND _out_text "ImageRegistry.region=${_profile_image_registry_region}\n")
    string(APPEND _out_text "ImageRegistry.section=${_profile_image_registry_section}\n")
    string(APPEND _out_text "FatFsStatic.size_bytes=${_profile_fatfs_size}\n")
    string(APPEND _out_text "FatFsStatic.region=${_profile_fatfs_region}\n")
    string(APPEND _out_text "FatFsStatic.section=${_profile_fatfs_section}\n")
    string(APPEND _out_text "StyleSlot.count=${_profile_style_slot_count}\n")
    string(APPEND _out_text "StyleSlot.total_bytes=${_profile_style_slot_bytes}\n")

    string(APPEND _out_text "\n[player_controller_profile]\n")
    foreach(_field IN LISTS _controller_profile_fields)
        set(_value_var "_controller_profile_${_field}")
        string(APPEND _out_text "${_field}=${${_value_var}}\n")
    endforeach()

    string(APPEND _out_text "\n[style_sheet_profile]\n")
    foreach(_field IN LISTS _style_sheet_profile_fields)
        set(_value_var "_style_sheet_profile_${_field}")
        string(APPEND _out_text "${_field}=${${_value_var}}\n")
    endforeach()

    string(APPEND _out_text "\n[sections]\n")
    foreach(_section_record IN LISTS _sections)
        string(REPLACE "|" ";" _section_fields "${_section_record}")
        list(GET _section_fields 0 _section_name)
        list(GET _section_fields 1 _section_addr)
        list(GET _section_fields 2 _section_size)
        list(GET _section_fields 3 _section_region)
        _h747_mem_hex(_section_addr_hex "${_section_addr}")
        string(APPEND _out_text "${_section_name} addr=${_section_addr_hex} size=${_section_size} region=${_section_region}\n")
    endforeach()

    string(APPEND _out_text "\n[key_symbols]\n")
    foreach(_record IN LISTS _key_symbols)
        string(REPLACE "|" ";" _fields "${_record}")
        list(GET _fields 0 _size)
        list(GET _fields 1 _addr)
        list(GET _fields 2 _type)
        list(GET _fields 3 _region)
        list(GET _fields 4 _section)
        list(GET _fields 5 _name)
        _h747_mem_hex(_addr_hex "${_addr}")
        string(APPEND _out_text "${_addr_hex} size=${_size} type=${_type} region=${_region} section=${_section} name=${_name}\n")
    endforeach()

    _h747_mem_append_top_symbols(_ram_d1_text "top_symbols.RAM_D1" _ram_d1_symbols "${H747_MEMORY_TOP_N}")
    string(APPEND _out_text "${_ram_d1_text}")
    _h747_mem_append_top_symbols(_ram_d2_text "top_symbols.RAM_D2" _ram_d2_symbols "${H747_MEMORY_TOP_N}")
    string(APPEND _out_text "${_ram_d2_text}")
    _h747_mem_append_top_symbols(_sdram_text "top_symbols.SDRAM" _sdram_symbols "${H747_MEMORY_TOP_N}")
    string(APPEND _out_text "${_sdram_text}")

    file(WRITE "${H747_MEMORY_OUT}" "${_out_text}")
endfunction()

if(H747_MEMORY_EVIDENCE_SCRIPT_MODE)
    _h747_mem_run_evidence()
    return()
endif()

option(H747_PLAYER_MD3_MEMORY_EVIDENCE
    "Generate H747 Player MD3 post-build memory evidence"
    ON)
option(H747_PLAYER_MD3_MEMORY_GATE
    "Fail H747 Player MD3 build when memory ownership structure is invalid"
    ON)
set(H747_PLAYER_MD3_MEMORY_TOP_N "32" CACHE STRING
    "Number of top RAM symbols to include in H747 Player MD3 memory evidence")
set(H747_PLAYER_MD3_RAM_D1_RECORD_BYTES "272256" CACHE STRING
    "Recorded H747 Player MD3 RAM_D1 baseline; evidence-only, not a hard gate")

function(h747_lab_add_player_md3_memory_evidence target_name)
    if(NOT target_name STREQUAL "h747_lab_player_md3")
        return()
    endif()
    if(NOT H747_PLAYER_MD3_MEMORY_EVIDENCE)
        return()
    endif()
    if(NOT CMAKE_SIZE)
        message(FATAL_ERROR "${target_name}: CMAKE_SIZE is required for memory evidence")
    endif()
    if(NOT CMAKE_NM)
        message(FATAL_ERROR "${target_name}: CMAKE_NM is required for memory evidence")
    endif()

    set(_memory_dir "${CMAKE_CURRENT_BINARY_DIR}/generated/memory")
    set(_memory_evidence "${_memory_dir}/player_md3_memory_evidence.txt")
    add_custom_command(TARGET ${target_name} POST_BUILD
        BYPRODUCTS "${_memory_evidence}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${_memory_dir}"
        COMMAND ${CMAKE_COMMAND}
            "-DH747_MEMORY_EVIDENCE_SCRIPT_MODE=ON"
            "-DH747_MEMORY_TARGET=${target_name}"
            "-DH747_MEMORY_ELF=$<TARGET_FILE:${target_name}>"
            "-DH747_MEMORY_BIN=${CMAKE_CURRENT_BINARY_DIR}/${target_name}.bin"
            "-DH747_MEMORY_OUT=${_memory_evidence}"
            "-DH747_MEMORY_TOP_N=${H747_PLAYER_MD3_MEMORY_TOP_N}"
            "-DH747_MEMORY_GATE=$<BOOL:${H747_PLAYER_MD3_MEMORY_GATE}>"
            "-DH747_MEMORY_RAM_D1_RECORD_BYTES=${H747_PLAYER_MD3_RAM_D1_RECORD_BYTES}"
            "-DH747_MEMORY_SIZE_TOOL=${CMAKE_SIZE}"
            "-DH747_MEMORY_NM_TOOL=${CMAKE_NM}"
            -P "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
        VERBATIM)
endfunction()
