#ifndef DAPLINK_PORT_MAIN_HPP
#define DAPLINK_PORT_MAIN_HPP

#ifndef CHARM_STM32H5_SUPPRESS_MATH_HEADER
#define CHARM_STM32H5_SUPPRESS_MATH_HEADER 1
#define DAPLINK_STM32H5_SUPPRESS_MATH_HEADER_LOCAL 1
#endif

#include "main.h"

#ifdef DAPLINK_STM32H5_SUPPRESS_MATH_HEADER_LOCAL
#undef DAPLINK_STM32H5_SUPPRESS_MATH_HEADER_LOCAL
#undef CHARM_STM32H5_SUPPRESS_MATH_HEADER
#endif

#endif
