set(PLAYER_MAIN_VIVID main.cpp)
set(PLAYER_MAIN_INK main_ink.cpp)
set(PLAYER_TARGET_VIVID charm-player-win-vivid)
set(PLAYER_TARGET_INK charm-player-win-ink)
set(PLAYER_TARGET_VIVID_MD3 charm-player-win-vivid-md3)

if (PLAYER_SCENARIO STREQUAL "ui_preview_ink")
    set(PLAYER_HOST_SCENARIO_TARGET ${PLAYER_TARGET_INK})
elseif (PLAYER_SCENARIO STREQUAL "ui_preview_vivid")
    set(PLAYER_HOST_SCENARIO_TARGET ${PLAYER_TARGET_VIVID})
elseif (PLAYER_SCENARIO STREQUAL "ui_preview_vivid_md3")
    set(PLAYER_HOST_SCENARIO_TARGET ${PLAYER_TARGET_VIVID_MD3})
else()
    message(FATAL_ERROR "Unsupported PLAYER_SCENARIO: ${PLAYER_SCENARIO}")
endif()
