#pragma once

#if defined(CHARM_VIVID_FEATURESET_FULL) && defined(CHARM_VIVID_FEATURESET_MCU_MIN)
#error "Only one of CHARM_VIVID_FEATURESET_FULL or CHARM_VIVID_FEATURESET_MCU_MIN can be defined."
#endif

#if defined(CHARM_VIVID_FEATURESET_MCU_MIN)
#define VIVID_WIDGET_DEFAULT 0
#else
#define VIVID_WIDGET_DEFAULT 1
#endif

#define VIVID_WIDGET(name)
#include "widgets.def"
#undef VIVID_WIDGET

#if defined(CHARM_VIVID_FEATURESET_MCU_MIN)
#undef CHARM_VIVID_ENABLE_WIDGET_Container
#undef CHARM_VIVID_ENABLE_WIDGET_ScrollContainer
#undef CHARM_VIVID_ENABLE_WIDGET_Label
#undef CHARM_VIVID_ENABLE_WIDGET_Button
#undef CHARM_VIVID_ENABLE_WIDGET_Checkbox
#undef CHARM_VIVID_ENABLE_WIDGET_Slider
#undef CHARM_VIVID_ENABLE_WIDGET_Switch
#undef CHARM_VIVID_ENABLE_WIDGET_Progress
#undef CHARM_VIVID_ENABLE_WIDGET_List
#undef CHARM_VIVID_ENABLE_WIDGET_ListItem
#undef CHARM_VIVID_ENABLE_WIDGET_Radio

#define CHARM_VIVID_ENABLE_WIDGET_Container 1
#define CHARM_VIVID_ENABLE_WIDGET_ScrollContainer 1
#define CHARM_VIVID_ENABLE_WIDGET_Label 1
#define CHARM_VIVID_ENABLE_WIDGET_Button 1
#define CHARM_VIVID_ENABLE_WIDGET_Checkbox 1
#define CHARM_VIVID_ENABLE_WIDGET_Slider 1
#define CHARM_VIVID_ENABLE_WIDGET_Switch 1
#define CHARM_VIVID_ENABLE_WIDGET_Progress 1
#define CHARM_VIVID_ENABLE_WIDGET_List 1
#define CHARM_VIVID_ENABLE_WIDGET_ListItem 1
#define CHARM_VIVID_ENABLE_WIDGET_Radio 1
#endif
