#pragma once

enum class Armv7aBringupPhase : unsigned char {
    kReset = 0,
    kBootCpuState,
    kMemoryProbePrepare,
    kMemoryProbeDescribe,
    kMmuActivate,
    kSmallPageProbe,
    kAttributeProbe,
    kIcacheProbe,
    kAbortSmoke,
    kExceptionSmoke,
    kDcacheProbe,
    kPageTableProbe,
    kSectionSplitProbe,
    kSvcSmoke,
    kTimerIrqSmoke,
    kSgiIrqSmoke,
    kSgiFiqSmoke,
    kSpecialIrqSmoke,
    kSgiIrqTimeoutSmoke,
    kUnexpectedIrqSmoke,
    kSgiFiqTimeoutSmoke,
    kKernelIngress,
    kSchedulerTickIngress,
    kRuntimeTrapFrame,
    kRuntimeTrapIngress,
    kRuntimeTrapMapping,
    kRuntimeTrapAdapter,
    kRuntimeTrapSeam,
    kRuntimeTrapLiveAdapter,
    kRuntimeTrapIngressAdapter,
    kRuntimeTrapCaller,
    kRuntimeTrapDispatch,
    kRuntimeCurrent,
    kRuntimeTrapContext,
    kRuntimeTrapRoundtrip,
    kRuntimeTrapFailure,
    kContextSwitchSmoke,
    kThreadRuntime,
    kSchedulerDispatch,
    kRuntimeBridge,
    kTaskSyscallFrame,
    kTaskSyscallDispatch,
    kTaskSyscallSurface,
    kTaskSyscallIngressAdapter,
    kTaskSyscallCaller,
    kTaskSyscallRoundtrip,
    kTaskSyscallGlue,
    kTaskSyscallFailure,
    kHandoffPrepare,
    kIdle,
};

const char* armv7a_bringup_phase_name(Armv7aBringupPhase phase);
Armv7aBringupPhase armv7a_current_bringup_phase();
Armv7aBringupPhase armv7a_last_completed_bringup_phase();
void armv7a_enter_bringup_phase(Armv7aBringupPhase phase);
void armv7a_complete_bringup_phase(Armv7aBringupPhase phase);
