set(H747_LAB_APP_NAME player_md3)
if(NOT DEFINED CHARM_PLAYER_FILE_FONTS)
    set(CHARM_PLAYER_FILE_FONTS ON CACHE BOOL "Enable Player MD3 file-font resource probe/backend on H747")
endif()
if(NOT DEFINED CHARM_PLAYER_MCU_RUNTIME_FILE_FONTS)
    set(CHARM_PLAYER_MCU_RUNTIME_FILE_FONTS OFF CACHE BOOL "Bind Player MD3 file fonts into the MCU render path")
endif()
if(NOT DEFINED CHARM_PLAYER_DEBUG_UI)
    set(CHARM_PLAYER_DEBUG_UI OFF CACHE BOOL "Enable Player MD3 debug UI modules on H747")
endif()
if(NOT DEFINED CHARM_PLAYER_LAYERED_TRANSITIONS)
    set(CHARM_PLAYER_LAYERED_TRANSITIONS OFF CACHE BOOL "Enable Player MD3 layered transitions on H747")
endif()
if(NOT DEFINED CHARM_PLAYER_COVER_THEME_EXTRACT)
    set(CHARM_PLAYER_COVER_THEME_EXTRACT OFF CACHE BOOL "Enable Player MD3 dynamic cover theme extraction on H747")
endif()
if(NOT DEFINED CHARM_PLAYER_LIST_COVER_CACHE_ENTRIES)
    set(CHARM_PLAYER_LIST_COVER_CACHE_ENTRIES 0 CACHE STRING "Player MD3 PRODUCT list cover cache entries on H747")
endif()
if(NOT DEFINED CHARM_PLAYER_LYRICS)
    set(CHARM_PLAYER_LYRICS OFF CACHE BOOL "Enable Player MD3 lyrics feature on H747")
endif()
include("${H747_LAB_ROOT}/cmake/h747_lab_player_md3_manifest.cmake")
set(H747_LAB_APP_SOURCES
    "${H747_LAB_ROOT}/apps/player_md3/player_md3.cpp"
    "${H747_LAB_ROOT}/apps/player_md3/player_md3_runtime.cpp"
    "${H747_LAB_ROOT}/apps/player_md3/player_md3_render_scheduler.cpp"
    "${H747_LAB_ROOT}/apps/player_md3/player_md3_console.cpp"
    "${H747_LAB_ROOT}/apps/player_md3/player_md3_input.cpp"
    "${H747_LAB_ROOT}/apps/player_md3/player_md3_memory.cpp"
    "${H747_LAB_ROOT}/apps/player_md3/player_md3_resource_probe.cpp"
    "${H747_LAB_ROOT}/apps/player_md3/player_md3_diag_render.cpp"
    "${H747_LAB_ROOT}/apps/player_md3/player_md3_diag_scene.cpp"
    "${H747_LAB_ROOT}/apps/player_md3/player_md3_diag_smoke.cpp"
    "${H747_LAB_ROOT}/apps/player_md3/player_md3_diag_status.cpp")
set(H747_LAB_APP_INCLUDE_DIRS
    "${H747_LAB_ROOT}/apps/player_md3"
    "${H747_LAB_ROOT}/apps/player"
    "${CHARM_ROOT}/Examples/project/player/app-vivid-MaterialDesign3")
h747_lab_collect_player_md3_modules(H747_LAB_APP_MODULE_SOURCES H747_LAB_APP_MODULE_BASE_DIRS)
include("${CHARM_ROOT}/Examples/project/player/cmake/player_md3_vivid_product.cmake")
set(H747_LAB_APP_VIVID_PROFILE "${CHARM_PLAYER_VIVID_PROFILE}")
set(H747_LAB_APP_COMPILE_DEFINITIONS
    CHARM_PLAYER_HOST_UI=0
    CHARM_PLAYER_HOST_STORAGE=0
    CHARM_PLAYER_HOST_COVER_DECODE=0
    CHARM_PLAYER_HOST_FILE_FONTS=0
    CHARM_PLAYER_ENABLE_FATFS_STORAGE=1
    CHARM_PLAYER_COVER_DECODE=0
    CHARM_PLAYER_FILE_FONTS=$<BOOL:${CHARM_PLAYER_FILE_FONTS}>
    CHARM_PLAYER_MCU_RUNTIME_FILE_FONTS=$<BOOL:${CHARM_PLAYER_MCU_RUNTIME_FILE_FONTS}>
    CHARM_PLAYER_MCU=1
    CHARM_PLAYER_MCU_STRICT=1
    CHARM_PLAYER_DEBUG_UI=$<BOOL:${CHARM_PLAYER_DEBUG_UI}>
    CHARM_PLAYER_LYRICS=$<BOOL:${CHARM_PLAYER_LYRICS}>
    CHARM_PLAYER_LAYERED_TRANSITIONS=$<BOOL:${CHARM_PLAYER_LAYERED_TRANSITIONS}>
    CHARM_PLAYER_COVER_THEME_EXTRACT=$<BOOL:${CHARM_PLAYER_COVER_THEME_EXTRACT}>
    CHARM_PLAYER_LIST_COVER_CACHE_ENTRIES=${CHARM_PLAYER_LIST_COVER_CACHE_ENTRIES}
    CHARM_VIVID_UNSUPPORTED_WIDGET_DIAG=1
    CHARM_VIVID_MEMORY_PROFILE_SYMBOLS=1
    CHARM_ENABLE_UI_VIVID=1
    CHARM_AUDIO_USE_VFS=1
    CHARM_AUDIO_SINK_I2S=1
    CHARM_AUDIO_ENABLE_MP3=1
    CHARM_AUDIO_ENABLE_FLAC=1
    CHARM_PLAYER_RESOURCE_FONT_SMALL_PX=14
    CHARM_PLAYER_RESOURCE_FONT_NORMAL_PX=18
    CHARM_PLAYER_RESOURCE_FONT_LARGE_PX=76)
set(H747_LAB_VIVID_FEATURESET PRODUCT)
