#pragma once

#include <cstdint>

#include "display_raster_service.hpp"
#include "player_display_hal.hpp"

import charm.system.clock;
import player.controller;
import player.display;
import player.platform;
import player.runtime;
import player.runtime_shell;

namespace h747::apps::player_md3 {

using PlayerRuntime = ::player::PlayerRuntime<::player::PlayerController, ::player::PlayerPage>;
using PlayerRuntimeShell = ::player::PlayerRuntimeShell<::player::PlayerController, ::player::PlayerPage>;

struct PlayerMd3State {
    bool display_ready{false};
    bool runtime_storage_ready{false};
    bool runtime_bootstrapped{false};
    bool last_render_ok{false};
    std::uint32_t frames{0};
    std::uint32_t status_ticks{0};
    std::uintptr_t render_surface{0};
    std::uintptr_t platform_storage{0};
    std::uintptr_t runtime_storage{0};
    std::uintptr_t icon_pixel_arena{0};
    std::uint32_t icon_pixel_arena_bytes{0};
    std::uint32_t external_pool_bytes{0};
    std::uint32_t render_sample0{0};
    std::uint32_t render_sample_center{0};
    std::uint32_t render_sample_last{0};
    std::uint32_t scene_cmd_count{0};
    std::uint32_t scene_cmd_capacity{0};
    std::uint32_t scene_cmd_overflowed{0};
    std::uint32_t scene_text_used{0};
    std::uint32_t scene_text_capacity{0};
    std::uint32_t scene_text_overflowed{0};
    std::uint32_t scene_exec_failed{0};
    std::uint32_t scene_exec_cmd_text{0};
    std::uint32_t scene_exec_cmd_rect{0};
    std::uint32_t scene_exec_cmd_image{0};
    std::uint32_t scene_exec_fail_text{0};
    std::uint32_t scene_exec_fail_image{0};
    std::uint32_t scene_batch_shrink{0};
    std::uint32_t scene_batch_shrink_rect{0};
    std::uint32_t scene_batch_shrink_text_path{0};
    std::uint32_t scene_exec_clip_failures{0};
    std::uint32_t scene_exec_batch_flushes{0};
    std::uint32_t scene_exec_dispatch_groups{0};
    std::uint32_t scene_exec_group_rect{0};
    std::uint32_t scene_exec_group_text{0};
    std::uint32_t scene_exec_group_image{0};
    std::uint32_t scene_exec_group_other{0};
    std::uint32_t scene_exec_cmd_line{0};
    std::uint32_t scene_exec_cmd_path{0};
    std::uint32_t scene_exec_cmd_other{0};
    std::uint32_t scene_exec_fail_other{0};
    std::uint32_t scene_exec_overflowed{0};
    std::uint32_t perf_time_available{0};
    std::uint32_t perf_time_frame_us{0};
    std::uint32_t perf_time_tick_us{0};
    std::uint32_t perf_time_render_us{0};
    std::uint32_t perf_time_record_us{0};
    std::uint32_t perf_time_execute_us{0};
    std::uint32_t perf_time_present_us{0};
    std::uint8_t render_throttle_enabled{1};
    std::uint8_t render_throttle_dirty{0};
    std::uint32_t render_throttle_skipped{0};
    std::uint32_t render_throttle_forced{0};
    std::uint32_t render_throttle_interval_ms{30000};
    std::uint32_t render_throttle_defer_ms{250};
    std::uint32_t render_throttle_last_render_ms{0};
    std::uint32_t render_throttle_dirty_since_ms{0};
    std::uint32_t style_rule_count{0};
    std::uint32_t style_rule_capacity{0};
    std::uint32_t style_metrics_used{0};
    std::uint32_t style_metrics_capacity{0};
    std::uint32_t style_metrics_overflowed{0};
    std::uint32_t smoke_ok{0};
    std::uint32_t smoke_mock_path{0};
    std::uint32_t smoke_boot_ok{0};
    std::uint32_t smoke_render_ok{0};
    std::uint32_t smoke_present_ok{0};
    std::uint32_t smoke_content_ok{0};
    std::uint32_t smoke_scene_ok{0};
    std::uint32_t smoke_frame_delta{0};
    std::uint32_t smoke_present_delta{0};
    std::uint32_t smoke_last_frames{0};
    std::uint32_t smoke_last_present{0};
    std::uint32_t input_polls{0};
    std::uint32_t input_events{0};
    std::uint32_t input_touch_events{0};
    std::uint32_t input_encoder_events{0};
    std::uint32_t input_button_events{0};
    std::uint8_t input_touch_probe_ok{0};
    std::uint8_t input_touch_ready{0};
    std::uint8_t input_touch_down{0};
    std::uint8_t input_last_id{0};
    std::uint8_t input_touch_profile{0};
    std::uint8_t input_touch_int_exti{0};
    std::uint8_t input_touch_int_level{0};
    std::uint8_t input_touch_int_last_level{0};
    std::uint8_t touch_cfg_auto_attempted{0};
    std::uint8_t touch_cfg_auto_written{0};
    std::uint8_t touch_cfg_auto_verify{0};
    std::uint8_t touch_cfg_auto_stage{0};
    std::uint8_t touch_cfg_auto_err{0};
    std::uint8_t touch_cfg_auto_before_valid{0};
    std::uint8_t touch_cfg_auto_after_valid{0};
    std::uint8_t touch_cfg_auto_force{0};
    std::uint32_t touch_cfg_auto_error_code{0};
    std::uint16_t input_last_x{0};
    std::uint16_t input_last_y{0};
    std::uint32_t input_touch_int_rise{0};
    std::uint32_t input_touch_int_fall{0};
    std::uint32_t input_touch_int_last_ms{0};
    std::int16_t input_encoder1_delta{0};
    std::int16_t input_encoder2_delta{0};
    std::uint8_t input_encoder1_button{0};
    std::uint8_t input_encoder2_button{0};
    std::uint8_t input_smoke_ok{0};
    std::uint32_t input_smoke_cmds{0};
    std::uint32_t input_smoke_before_events{0};
    std::uint32_t input_smoke_after_events{0};
    std::uint32_t input_smoke_frames{0};
    std::uint32_t input_smoke_exec_fail{0};
    std::uint32_t input_route_console_commands{0};
    std::uint32_t input_route_touch_pointers{0};
    std::uint32_t input_route_encoder_commands{0};
    std::uint32_t input_route_button_commands{0};
    std::uint8_t input_route_last_source{0};
    std::uint8_t input_route_last_kind{0};
    std::uint8_t input_route_last_code{0};
    std::uint8_t touch_monitor_enabled{0};
    std::uint8_t touch_monitor_pause_render{0};
    std::uint32_t touch_monitor_events{0};
    std::uint32_t touch_oob_count{0};
    std::uint16_t touch_oob_raw_x{0};
    std::uint16_t touch_oob_raw_y{0};
    std::uint16_t touch_oob_clamped_x{0};
    std::uint16_t touch_oob_clamped_y{0};
    std::uint16_t touch_oob_max_x{0};
    std::uint16_t touch_oob_max_y{0};
    std::uint8_t touch_sample_enabled{0};
    std::uint8_t touch_sample_pause_render{0};
    std::uint32_t touch_sample_count{0};
    std::uint32_t touch_sample_ready_hits{0};
    std::uint32_t touch_sample_int_changes{0};
    std::uint32_t touch_sample_last_ms{0};
    std::uint8_t touch_sample_last_int{0};
    std::uint16_t touch_sample_raw_min_x{0};
    std::uint16_t touch_sample_raw_min_y{0};
    std::uint16_t touch_sample_raw_max_x{0};
    std::uint16_t touch_sample_raw_max_y{0};
    std::uint16_t touch_sample_filtered_x{0};
    std::uint16_t touch_sample_filtered_y{0};
    std::uint8_t touch_dispatch_enabled{0};
    std::uint8_t touch_dispatch_last_action{0};
    std::uint8_t touch_dispatch_once_active{0};
    std::uint8_t touch_dispatch_once_in_sequence{0};
    std::uint32_t touch_dispatch_blocked{0};
    std::uint8_t touch_map_mode{0};
    std::uint8_t touch_map_swap_xy{0};
    std::uint8_t touch_map_invert_x{0};
    std::uint8_t touch_map_invert_y{0};
    std::uint16_t touch_map_raw_x{0};
    std::uint16_t touch_map_raw_y{0};
    std::uint16_t touch_map_ui_x{0};
    std::uint16_t touch_map_ui_y{0};
    std::uint16_t touch_map_raw_w{720};
    std::uint16_t touch_map_raw_h{1280};
    std::uint16_t touch_map_display_w{720};
    std::uint16_t touch_map_display_h{1280};
    std::uint32_t touch_ui_sent{0};
    std::uint32_t touch_ui_blocked{0};
    std::uint32_t touch_ui_fault_guard{0};
    std::uint8_t touch_ui_last_action{0};
    std::uint32_t touch_latency_samples{0};
    std::uint32_t touch_latency_last_int_to_poll_ms{0};
    std::uint32_t touch_latency_last_poll_to_dispatch_ms{0};
    std::uint32_t touch_latency_last_dispatch_to_frame_ms{0};
    std::uint32_t touch_latency_max_int_to_poll_ms{0};
    std::uint32_t touch_latency_max_poll_to_dispatch_ms{0};
    std::uint32_t touch_latency_max_dispatch_to_frame_ms{0};
    std::uint32_t touch_latency_last_poll_ms{0};
    std::uint32_t touch_latency_last_dispatch_ms{0};
    std::uint32_t touch_latency_last_frame_ms{0};
    std::uint8_t storage_ready{0};
    std::uint8_t storage_fat_probe_ok{0};
    std::uint8_t storage_attempted{0};
    std::uint8_t storage_initialized{0};
    std::uint8_t storage_block_device_ready{0};
    std::uint8_t storage_partition_auto{0};
    std::uint8_t audio_ready{0};
    std::uint8_t audio_dma_ready{0};
    std::uint32_t storage_blocks{0};
    std::uint32_t storage_part_lba{0};
    std::uint32_t storage_reads{0};
    std::uint32_t storage_read_fails{0};
    std::uint32_t storage_init_status{0};
    std::uint32_t storage_last_hal_status{0};
    std::uint32_t storage_last_error{0};
    std::uint32_t storage_card_state{0};
    std::uint32_t storage_block_size{0};
    std::uint32_t storage_wait_timeouts{0};
    std::uint32_t storage_last_lba{0};
    std::uint32_t storage_last_count{0};
    std::uint32_t storage_sta{0};
    std::uint32_t storage_selected_bus_width{0};
    std::uint32_t storage_wide_status_8{0};
    std::uint32_t storage_wide_status_4{0};
    std::uint32_t storage_wide_status_1{0};
    std::uint32_t audio_i2s_status{0};
    std::uint32_t audio_dma_status{0};
    std::uint32_t audio_dma_half_count{0};
    std::uint32_t audio_dma_full_count{0};
    std::uint32_t audio_underrun_count{0};
    std::uint8_t resource_probe_done{0};
    std::uint8_t fs_mount_ok{0};
    std::uint8_t fs_has_tracks{0};
    std::uint8_t font_primary_open{0};
    std::uint8_t font_fallback_open{0};
    std::uint8_t font_cache_ready{0};
    std::uint8_t font_config_kind{0};
    std::uint8_t font_primary_configured{0};
    std::uint8_t font_fallback_configured{0};
    std::uint8_t font_compat_open{0};
    std::uint8_t cover_folder_found{0};
    std::uint8_t cover_decode_ok{0};
    std::uint8_t media_first_open{0};
    std::uint8_t media_duration_ok{0};
    std::uint8_t media_track_ready{0};
    std::uint32_t fs_track_count{0};
    std::int32_t fs_mount_err{0};
    std::int32_t font_err{0};
    std::int32_t cover_err{0};
    std::int32_t media_err{0};
    std::uint32_t cover_width{0};
    std::uint32_t cover_height{0};
    std::uint8_t playback_player_state{0};
    std::uint8_t playback_running{0};
    std::uint8_t playback_track_ready{0};
    std::uint8_t playback_play_mode{0};
    std::int32_t playback_track_index{0};
    std::int32_t playback_track_count{0};
    std::int32_t playback_current_sec{0};
    std::int32_t playback_duration_sec{0};
    std::uint32_t playback_dma_callbacks{0};
    std::uint32_t playback_underruns{0};
    std::int32_t playback_last_error_stage{0};
    std::int32_t playback_last_error{0};
    std::uint8_t playback_smoke_ok{0};
    std::uint32_t playback_smoke_before_callbacks{0};
    std::uint32_t playback_smoke_after_callbacks{0};
    std::uint32_t playback_smoke_frames{0};
    std::uint8_t playback_smoke_saw_playing{0};
    std::int32_t playback_smoke_error_stage{0};
    std::int32_t playback_smoke_error{0};
    std::uint32_t render_bg_pixel{0};
    std::uint32_t render_non_bg_pixels{0};
    std::uint32_t render_content_min_x{0};
    std::uint32_t render_content_min_y{0};
    std::uint32_t render_content_max_x{0};
    std::uint32_t render_content_max_y{0};
    h747::display::RasterPanel panel{};
    h747::apps::player::PlayerRasterDisplaySinkState sink_state{};
};

PlayerMd3State& state() noexcept;
::player::PlayerController& controller_ref() noexcept;
PlayerRuntime* runtime_ref() noexcept;
PlayerRuntimeShell* shell_ref() noexcept;
::player::PlayerDisplaySink& sink_ref() noexcept;
charm::system::Clock& clock_ref() noexcept;
::player::PlayerRuntimeConfig<::player::PlayerPage> runtime_config() noexcept;

void init_runtime() noexcept;
void loop_runtime() noexcept;
bool render_frame() noexcept;
bool force_render_frame() noexcept;
void runtime_step_only() noexcept;
void refresh_playback_probe_state() noexcept;

enum class PlayerMd3PlaybackControl : std::uint8_t {
    Pause,
    Resume,
    Stop,
};

[[nodiscard]] bool dispatch_runtime_playback_control(PlayerMd3PlaybackControl control) noexcept;
[[nodiscard]] bool select_runtime_track_index(int index) noexcept;
[[nodiscard]] bool seek_runtime_playback(int target_sec) noexcept;

} // namespace h747::apps::player_md3
