#pragma once

#include <cstdint>

#include "display_raster_service.hpp"
#include "player_display_hal.hpp"

import charm.system.clock;
import player.controller;
import player.display;
import player.platform;
import player.runtime;
import player.runtime_shell;

namespace h747::apps::player_md3 {

using PlayerRuntime = ::player::PlayerRuntime<::player::PlayerController, ::player::PlayerPage>;
using PlayerRuntimeShell = ::player::PlayerRuntimeShell<::player::PlayerController, ::player::PlayerPage>;

struct PlayerMd3State {
    bool display_ready{false};
    bool runtime_storage_ready{false};
    bool runtime_bootstrapped{false};
    bool last_render_ok{false};
    std::uint32_t frames{0};
    std::uint32_t status_ticks{0};
    std::uintptr_t render_surface{0};
    std::uintptr_t platform_storage{0};
    std::uintptr_t runtime_storage{0};
    std::uintptr_t icon_pixel_arena{0};
    std::uint32_t icon_pixel_arena_bytes{0};
    std::uint32_t external_pool_bytes{0};
    std::uint32_t render_sample0{0};
    std::uint32_t render_sample_center{0};
    std::uint32_t render_sample_last{0};
    std::uint32_t scene_cmd_count{0};
    std::uint32_t scene_cmd_capacity{0};
    std::uint32_t scene_cmd_overflowed{0};
    std::uint32_t scene_text_used{0};
    std::uint32_t scene_text_capacity{0};
    std::uint32_t scene_text_overflowed{0};
    std::uint32_t scene_exec_failed{0};
    std::uint32_t scene_exec_cmd_text{0};
    std::uint32_t scene_exec_cmd_rect{0};
    std::uint32_t scene_exec_cmd_image{0};
    std::uint32_t scene_exec_fail_text{0};
    std::uint32_t scene_exec_fail_image{0};
    std::uint32_t scene_batch_shrink{0};
    std::uint32_t scene_batch_shrink_rect{0};
    std::uint32_t scene_batch_shrink_text_path{0};
    std::uint32_t scene_exec_clip_failures{0};
    std::uint32_t scene_exec_batch_flushes{0};
    std::uint32_t scene_exec_dispatch_groups{0};
    std::uint32_t scene_exec_group_rect{0};
    std::uint32_t scene_exec_group_text{0};
    std::uint32_t scene_exec_group_image{0};
    std::uint32_t scene_exec_group_other{0};
    std::uint32_t scene_exec_cmd_line{0};
    std::uint32_t scene_exec_cmd_path{0};
    std::uint32_t scene_exec_cmd_other{0};
    std::uint32_t scene_exec_fail_other{0};
    std::uint32_t scene_exec_overflowed{0};
    std::uint32_t style_rule_count{0};
    std::uint32_t style_rule_capacity{0};
    std::uint32_t style_metrics_used{0};
    std::uint32_t style_metrics_capacity{0};
    std::uint32_t style_metrics_overflowed{0};
    std::uint32_t smoke_ok{0};
    std::uint32_t smoke_mock_path{0};
    std::uint32_t smoke_boot_ok{0};
    std::uint32_t smoke_render_ok{0};
    std::uint32_t smoke_present_ok{0};
    std::uint32_t smoke_content_ok{0};
    std::uint32_t smoke_scene_ok{0};
    std::uint32_t smoke_frame_delta{0};
    std::uint32_t smoke_present_delta{0};
    std::uint32_t smoke_last_frames{0};
    std::uint32_t smoke_last_present{0};
    std::uint32_t input_polls{0};
    std::uint32_t input_events{0};
    std::uint32_t input_touch_events{0};
    std::uint32_t input_encoder_events{0};
    std::uint32_t input_button_events{0};
    std::uint8_t input_touch_probe_ok{0};
    std::uint8_t input_touch_ready{0};
    std::uint8_t input_touch_down{0};
    std::uint8_t input_last_id{0};
    std::uint16_t input_last_x{0};
    std::uint16_t input_last_y{0};
    std::int16_t input_encoder1_delta{0};
    std::int16_t input_encoder2_delta{0};
    std::uint8_t input_encoder1_button{0};
    std::uint8_t input_encoder2_button{0};
    std::uint8_t input_smoke_ok{0};
    std::uint32_t input_smoke_cmds{0};
    std::uint32_t input_smoke_before_events{0};
    std::uint32_t input_smoke_after_events{0};
    std::uint32_t input_smoke_frames{0};
    std::uint32_t input_smoke_exec_fail{0};
    std::uint32_t input_route_console_commands{0};
    std::uint32_t input_route_touch_pointers{0};
    std::uint32_t input_route_encoder_commands{0};
    std::uint32_t input_route_button_commands{0};
    std::uint8_t input_route_last_source{0};
    std::uint8_t input_route_last_kind{0};
    std::uint8_t input_route_last_code{0};
    std::uint8_t storage_ready{0};
    std::uint8_t storage_fat_probe_ok{0};
    std::uint8_t storage_attempted{0};
    std::uint8_t storage_initialized{0};
    std::uint8_t storage_block_device_ready{0};
    std::uint8_t storage_partition_auto{0};
    std::uint8_t audio_ready{0};
    std::uint8_t audio_dma_ready{0};
    std::uint32_t storage_blocks{0};
    std::uint32_t storage_part_lba{0};
    std::uint32_t storage_reads{0};
    std::uint32_t storage_read_fails{0};
    std::uint32_t storage_init_status{0};
    std::uint32_t storage_last_hal_status{0};
    std::uint32_t storage_last_error{0};
    std::uint32_t storage_card_state{0};
    std::uint32_t storage_block_size{0};
    std::uint32_t storage_wait_timeouts{0};
    std::uint32_t storage_last_lba{0};
    std::uint32_t storage_last_count{0};
    std::uint32_t storage_sta{0};
    std::uint32_t storage_selected_bus_width{0};
    std::uint32_t storage_wide_status_8{0};
    std::uint32_t storage_wide_status_4{0};
    std::uint32_t storage_wide_status_1{0};
    std::uint32_t audio_i2s_status{0};
    std::uint32_t audio_dma_status{0};
    std::uint32_t audio_dma_half_count{0};
    std::uint32_t audio_dma_full_count{0};
    std::uint32_t audio_underrun_count{0};
    std::uint8_t resource_probe_done{0};
    std::uint8_t fs_mount_ok{0};
    std::uint8_t fs_has_tracks{0};
    std::uint8_t font_primary_open{0};
    std::uint8_t font_fallback_open{0};
    std::uint8_t font_cache_ready{0};
    std::uint8_t cover_folder_found{0};
    std::uint8_t cover_decode_ok{0};
    std::uint8_t media_first_open{0};
    std::uint8_t media_duration_ok{0};
    std::uint8_t media_track_ready{0};
    std::uint32_t fs_track_count{0};
    std::int32_t fs_mount_err{0};
    std::int32_t font_err{0};
    std::int32_t cover_err{0};
    std::int32_t media_err{0};
    std::uint32_t cover_width{0};
    std::uint32_t cover_height{0};
    std::uint8_t playback_player_state{0};
    std::uint8_t playback_running{0};
    std::uint8_t playback_track_ready{0};
    std::uint32_t playback_dma_callbacks{0};
    std::uint32_t playback_underruns{0};
    std::int32_t playback_last_error_stage{0};
    std::int32_t playback_last_error{0};
    std::uint8_t playback_smoke_ok{0};
    std::uint32_t playback_smoke_before_callbacks{0};
    std::uint32_t playback_smoke_after_callbacks{0};
    std::uint32_t playback_smoke_frames{0};
    std::uint8_t playback_smoke_saw_playing{0};
    std::int32_t playback_smoke_error_stage{0};
    std::int32_t playback_smoke_error{0};
    std::uint32_t render_bg_pixel{0};
    std::uint32_t render_non_bg_pixels{0};
    std::uint32_t render_content_min_x{0};
    std::uint32_t render_content_min_y{0};
    std::uint32_t render_content_max_x{0};
    std::uint32_t render_content_max_y{0};
    h747::display::RasterPanel panel{};
    h747::apps::player::PlayerRasterDisplaySinkState sink_state{};
};

PlayerMd3State& state() noexcept;
::player::PlayerController& controller_ref() noexcept;
PlayerRuntime* runtime_ref() noexcept;
PlayerRuntimeShell* shell_ref() noexcept;
::player::PlayerDisplaySink& sink_ref() noexcept;
charm::system::Clock& clock_ref() noexcept;
::player::PlayerRuntimeConfig<::player::PlayerPage> runtime_config() noexcept;

void init_runtime() noexcept;
void loop_runtime() noexcept;
bool render_frame() noexcept;
void refresh_playback_probe_state() noexcept;

} // namespace h747::apps::player_md3
