set(_VIVID_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}")

macro(vivid_cache_default name type default_value doc)
    if (NOT DEFINED ${name})
        set(${name} "${default_value}" CACHE ${type} "${doc}")
    endif()
endmacro()

function(vivid_bool_literal out_var value)
    if (${value})
        set(${out_var} 1 PARENT_SCOPE)
    else()
        set(${out_var} 0 PARENT_SCOPE)
    endif()
endfunction()

function(vivid_collect_modules target_name module_list_var base_dirs_var)
    if (NOT CHARM_ENABLE_UI_VIVID)
        return()
    endif()

    vivid_cache_default(CHARM_VIVID_SCREEN_WIDTH STRING 480 "Vivid screen width")
    vivid_cache_default(CHARM_VIVID_SCREEN_HEIGHT STRING 800 "Vivid screen height")
    vivid_cache_default(CHARM_VIVID_SCREEN_PIXEL_FORMAT STRING RGB888 "Vivid screen pixel format")
    set_property(CACHE CHARM_VIVID_SCREEN_PIXEL_FORMAT PROPERTY STRINGS RGB888 RGB565)
    math(EXPR _vivid_default_layer_cache_width "${CHARM_VIVID_SCREEN_WIDTH} / 2")
    math(EXPR _vivid_default_layer_cache_height "${CHARM_VIVID_SCREEN_HEIGHT} / 2")
    vivid_cache_default(CHARM_VIVID_LAYER_CACHE_SLOTS STRING 1 "Vivid layer cache slot count")
    vivid_cache_default(CHARM_VIVID_LAYER_CACHE_WIDTH STRING ${_vivid_default_layer_cache_width} "Vivid layer cache width")
    vivid_cache_default(CHARM_VIVID_LAYER_CACHE_HEIGHT STRING ${_vivid_default_layer_cache_height} "Vivid layer cache height")
    vivid_cache_default(CHARM_VIVID_ENABLE_FLOAT_WIDGETS BOOL ON "Enable float-backed vivid widgets")
    vivid_cache_default(CHARM_VIVID_SOA_MAX_NODES STRING 256 "Vivid SoA max node count")

    target_compile_definitions(${target_name} PRIVATE CHARM_VIVID_SOA_ONLY=1 CHARM_VIVID_KERNEL_SOA=1)
    vivid_bool_literal(_vivid_enable_float_widgets ${CHARM_VIVID_ENABLE_FLOAT_WIDGETS})
    if (CHARM_VIVID_FEATURESET STREQUAL "MCU_MIN")
        set(VIVID_FEATURESET_ENUM "mcu_min")
        set(VIVID_IS_MCU_MIN 1)
    elseif (CHARM_VIVID_FEATURESET STREQUAL "FULL")
        set(VIVID_FEATURESET_ENUM "full")
        set(VIVID_IS_MCU_MIN 0)
    else()
        message(FATAL_ERROR "Unknown CHARM_VIVID_FEATURESET: ${CHARM_VIVID_FEATURESET}")
    endif()

    if (CHARM_VIVID_SCREEN_PIXEL_FORMAT STREQUAL "RGB565")
        set(VIVID_SCREEN_PIXEL_FORMAT "PixelFormat::RGB565")
    elseif (CHARM_VIVID_SCREEN_PIXEL_FORMAT STREQUAL "RGB888")
        set(VIVID_SCREEN_PIXEL_FORMAT "PixelFormat::RGB888")
    else()
        message(FATAL_ERROR "Unknown CHARM_VIVID_SCREEN_PIXEL_FORMAT: ${CHARM_VIVID_SCREEN_PIXEL_FORMAT}")
    endif()

    set(VIVID_SCREEN_WIDTH ${CHARM_VIVID_SCREEN_WIDTH})
    set(VIVID_SCREEN_HEIGHT ${CHARM_VIVID_SCREEN_HEIGHT})
    set(VIVID_LAYER_CACHE_SLOTS ${CHARM_VIVID_LAYER_CACHE_SLOTS})
    set(VIVID_LAYER_CACHE_WIDTH ${CHARM_VIVID_LAYER_CACHE_WIDTH})
    set(VIVID_LAYER_CACHE_HEIGHT ${CHARM_VIVID_LAYER_CACHE_HEIGHT})
    set(VIVID_ENABLE_FLOAT_WIDGETS ${_vivid_enable_float_widgets})
    set(VIVID_SOA_MAX_NODES ${CHARM_VIVID_SOA_MAX_NODES})

    set(SOA_POOL_CAP_DEFAULT "kDefaultPoolCap")
    set(SOA_TEXT_ARENA_BYTES "kDefaultTextArenaBytes")
    function(soa_compute_cap out_var peak floor scale_num scale_den extra)
        math(EXPR _cap_raw "(${peak} * ${scale_num} + (${scale_den} - 1)) / ${scale_den} + ${extra}")
        if (_cap_raw LESS ${floor})
            set(_cap_raw ${floor})
        endif()
        set(${out_var} ${_cap_raw} PARENT_SCOPE)
    endfunction()

    set(SOA_POOL_PEAK_LABEL 56)
    set(SOA_POOL_PEAK_BUTTON 24)
    set(SOA_POOL_PEAK_IMAGE 8)
    set(SOA_POOL_PEAK_TEXT_INPUT 1)
    set(SOA_POOL_PEAK_TEXT_AREA 1)
    set(SOA_POOL_PEAK_NUMBER_INPUT 1)
    set(SOA_POOL_PEAK_SEGMENTED_CONTROL 1)
    set(SOA_POOL_PEAK_STEPPER 1)
    set(SOA_POOL_PEAK_TOGGLE_GROUP 1)
    set(SOA_POOL_PEAK_CHECKBOX 2)
    set(SOA_POOL_PEAK_RADIO 1)
    set(SOA_POOL_PEAK_LIST_ITEM 10)
    set(SOA_POOL_PEAK_TEXT_LIST 1)
    set(SOA_POOL_PEAK_LIST_VIEW 1)
    set(SOA_POOL_PEAK_TABLE_VIEW 1)
    set(SOA_POOL_PEAK_TREE_VIEW 1)
    set(SOA_POOL_PEAK_NUMBER_LIST 1)
    set(SOA_POOL_PEAK_ROLLER 1)
    set(SOA_POOL_PEAK_SWITCH 1)
    set(SOA_POOL_PEAK_SLIDER 8)
    set(SOA_POOL_PEAK_PROGRESS 6)
    set(SOA_POOL_PEAK_SCROLLBAR 2)
    set(SOA_POOL_PEAK_LIST 1)
    set(SOA_POOL_PEAK_SCROLL_CONTAINER 2)
    set(SOA_POOL_PEAK_SPINNER 1)

    set(SOA_POOL_FLOOR_LABEL 1)
    set(SOA_POOL_FLOOR_BUTTON 1)
    set(SOA_POOL_FLOOR_IMAGE 1)
    set(SOA_POOL_FLOOR_TEXT_INPUT 1)
    set(SOA_POOL_FLOOR_TEXT_AREA 1)
    set(SOA_POOL_FLOOR_NUMBER_INPUT 1)
    set(SOA_POOL_FLOOR_SEGMENTED_CONTROL 1)
    set(SOA_POOL_FLOOR_STEPPER 1)
    set(SOA_POOL_FLOOR_TOGGLE_GROUP 1)
    set(SOA_POOL_FLOOR_CHECKBOX 1)
    set(SOA_POOL_FLOOR_RADIO 1)
    set(SOA_POOL_FLOOR_LIST_ITEM 1)
    set(SOA_POOL_FLOOR_TEXT_LIST 1)
    set(SOA_POOL_FLOOR_LIST_VIEW 1)
    set(SOA_POOL_FLOOR_TABLE_VIEW 1)
    set(SOA_POOL_FLOOR_TREE_VIEW 1)
    set(SOA_POOL_FLOOR_NUMBER_LIST 1)
    set(SOA_POOL_FLOOR_ROLLER 1)
    set(SOA_POOL_FLOOR_SWITCH 1)
    set(SOA_POOL_FLOOR_SLIDER 1)
    set(SOA_POOL_FLOOR_PROGRESS 1)
    set(SOA_POOL_FLOOR_SCROLLBAR 1)
    set(SOA_POOL_FLOOR_LIST 1)
    set(SOA_POOL_FLOOR_SCROLL_CONTAINER 1)
    set(SOA_POOL_FLOOR_SPINNER 1)

    if (CHARM_VIVID_FEATURESET STREQUAL "MCU_MIN")
        soa_compute_cap(SOA_POOL_CAP_LABEL "${SOA_POOL_PEAK_LABEL}" "${SOA_POOL_FLOOR_LABEL}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_BUTTON "${SOA_POOL_PEAK_BUTTON}" "${SOA_POOL_FLOOR_BUTTON}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_IMAGE "${SOA_POOL_PEAK_IMAGE}" "${SOA_POOL_FLOOR_IMAGE}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_TEXT_INPUT "${SOA_POOL_PEAK_TEXT_INPUT}" "${SOA_POOL_FLOOR_TEXT_INPUT}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_TEXT_AREA "${SOA_POOL_PEAK_TEXT_AREA}" "${SOA_POOL_FLOOR_TEXT_AREA}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_NUMBER_INPUT "${SOA_POOL_PEAK_NUMBER_INPUT}" "${SOA_POOL_FLOOR_NUMBER_INPUT}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_SEGMENTED_CONTROL "${SOA_POOL_PEAK_SEGMENTED_CONTROL}" "${SOA_POOL_FLOOR_SEGMENTED_CONTROL}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_STEPPER "${SOA_POOL_PEAK_STEPPER}" "${SOA_POOL_FLOOR_STEPPER}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_TOGGLE_GROUP "${SOA_POOL_PEAK_TOGGLE_GROUP}" "${SOA_POOL_FLOOR_TOGGLE_GROUP}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_CHECKBOX "${SOA_POOL_PEAK_CHECKBOX}" "${SOA_POOL_FLOOR_CHECKBOX}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_RADIO "${SOA_POOL_PEAK_RADIO}" "${SOA_POOL_FLOOR_RADIO}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_LIST_ITEM "${SOA_POOL_PEAK_LIST_ITEM}" "${SOA_POOL_FLOOR_LIST_ITEM}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_TEXT_LIST "${SOA_POOL_PEAK_TEXT_LIST}" "${SOA_POOL_FLOOR_TEXT_LIST}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_LIST_VIEW "${SOA_POOL_PEAK_LIST_VIEW}" "${SOA_POOL_FLOOR_LIST_VIEW}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_TABLE_VIEW "${SOA_POOL_PEAK_TABLE_VIEW}" "${SOA_POOL_FLOOR_TABLE_VIEW}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_TREE_VIEW "${SOA_POOL_PEAK_TREE_VIEW}" "${SOA_POOL_FLOOR_TREE_VIEW}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_NUMBER_LIST "${SOA_POOL_PEAK_NUMBER_LIST}" "${SOA_POOL_FLOOR_NUMBER_LIST}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_ROLLER "${SOA_POOL_PEAK_ROLLER}" "${SOA_POOL_FLOOR_ROLLER}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_SWITCH "${SOA_POOL_PEAK_SWITCH}" "${SOA_POOL_FLOOR_SWITCH}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_SLIDER "${SOA_POOL_PEAK_SLIDER}" "${SOA_POOL_FLOOR_SLIDER}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_PROGRESS "${SOA_POOL_PEAK_PROGRESS}" "${SOA_POOL_FLOOR_PROGRESS}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_SCROLLBAR "${SOA_POOL_PEAK_SCROLLBAR}" "${SOA_POOL_FLOOR_SCROLLBAR}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_LIST "${SOA_POOL_PEAK_LIST}" "${SOA_POOL_FLOOR_LIST}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_SCROLL_CONTAINER "${SOA_POOL_PEAK_SCROLL_CONTAINER}" "${SOA_POOL_FLOOR_SCROLL_CONTAINER}" 11 10 1)
        soa_compute_cap(SOA_POOL_CAP_SPINNER "${SOA_POOL_PEAK_SPINNER}" "${SOA_POOL_FLOOR_SPINNER}" 11 10 1)
    elseif (CHARM_VIVID_FEATURESET STREQUAL "FULL")
        set(SOA_TEXT_ARENA_BYTES 32768)
        soa_compute_cap(SOA_POOL_CAP_LABEL "${SOA_POOL_PEAK_LABEL}" "${SOA_POOL_FLOOR_LABEL}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_BUTTON "${SOA_POOL_PEAK_BUTTON}" "${SOA_POOL_FLOOR_BUTTON}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_IMAGE "${SOA_POOL_PEAK_IMAGE}" "${SOA_POOL_FLOOR_IMAGE}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_TEXT_INPUT "${SOA_POOL_PEAK_TEXT_INPUT}" "${SOA_POOL_FLOOR_TEXT_INPUT}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_TEXT_AREA "${SOA_POOL_PEAK_TEXT_AREA}" "${SOA_POOL_FLOOR_TEXT_AREA}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_NUMBER_INPUT "${SOA_POOL_PEAK_NUMBER_INPUT}" "${SOA_POOL_FLOOR_NUMBER_INPUT}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_SEGMENTED_CONTROL "${SOA_POOL_PEAK_SEGMENTED_CONTROL}" "${SOA_POOL_FLOOR_SEGMENTED_CONTROL}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_STEPPER "${SOA_POOL_PEAK_STEPPER}" "${SOA_POOL_FLOOR_STEPPER}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_TOGGLE_GROUP "${SOA_POOL_PEAK_TOGGLE_GROUP}" "${SOA_POOL_FLOOR_TOGGLE_GROUP}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_CHECKBOX "${SOA_POOL_PEAK_CHECKBOX}" "${SOA_POOL_FLOOR_CHECKBOX}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_RADIO "${SOA_POOL_PEAK_RADIO}" "${SOA_POOL_FLOOR_RADIO}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_LIST_ITEM "${SOA_POOL_PEAK_LIST_ITEM}" "${SOA_POOL_FLOOR_LIST_ITEM}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_TEXT_LIST "${SOA_POOL_PEAK_TEXT_LIST}" "${SOA_POOL_FLOOR_TEXT_LIST}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_LIST_VIEW "${SOA_POOL_PEAK_LIST_VIEW}" "${SOA_POOL_FLOOR_LIST_VIEW}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_TABLE_VIEW "${SOA_POOL_PEAK_TABLE_VIEW}" "${SOA_POOL_FLOOR_TABLE_VIEW}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_TREE_VIEW "${SOA_POOL_PEAK_TREE_VIEW}" "${SOA_POOL_FLOOR_TREE_VIEW}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_NUMBER_LIST "${SOA_POOL_PEAK_NUMBER_LIST}" "${SOA_POOL_FLOOR_NUMBER_LIST}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_ROLLER "${SOA_POOL_PEAK_ROLLER}" "${SOA_POOL_FLOOR_ROLLER}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_SWITCH "${SOA_POOL_PEAK_SWITCH}" "${SOA_POOL_FLOOR_SWITCH}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_SLIDER "${SOA_POOL_PEAK_SLIDER}" "${SOA_POOL_FLOOR_SLIDER}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_PROGRESS "${SOA_POOL_PEAK_PROGRESS}" "${SOA_POOL_FLOOR_PROGRESS}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_SCROLLBAR "${SOA_POOL_PEAK_SCROLLBAR}" "${SOA_POOL_FLOOR_SCROLLBAR}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_LIST "${SOA_POOL_PEAK_LIST}" "${SOA_POOL_FLOOR_LIST}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_SCROLL_CONTAINER "${SOA_POOL_PEAK_SCROLL_CONTAINER}" "${SOA_POOL_FLOOR_SCROLL_CONTAINER}" 5 4 2)
        soa_compute_cap(SOA_POOL_CAP_SPINNER "${SOA_POOL_PEAK_SPINNER}" "${SOA_POOL_FLOOR_SPINNER}" 5 4 2)
    endif()

    set(vivid_pool_caps_output_dir "${CMAKE_CURRENT_BINARY_DIR}/generated/vivid")
    file(MAKE_DIRECTORY "${vivid_pool_caps_output_dir}")
    set(vivid_features_header "${vivid_pool_caps_output_dir}/vivid_features.generated.hpp")
    set(vivid_config_cppm "${vivid_pool_caps_output_dir}/config.generated.cppm")
    set(vivid_pool_caps_cppm "${vivid_pool_caps_output_dir}/soa_pool_caps.cppm")
    configure_file(
        "${_VIVID_CMAKE_DIR}/cmake/features.generated.hpp.in"
        "${vivid_features_header}"
        @ONLY)
    configure_file(
        "${_VIVID_CMAKE_DIR}/cmake/config.generated.cppm.in"
        "${vivid_config_cppm}"
        @ONLY)
    configure_file(
        "${_VIVID_CMAKE_DIR}/cmake/soa_pool_caps.cppm.in"
        "${vivid_pool_caps_cppm}"
        @ONLY)

    list(APPEND ${module_list_var} "${vivid_config_cppm}")
    list(APPEND ${module_list_var} "${vivid_pool_caps_cppm}")
    set(${base_dirs_var} "${${base_dirs_var}}" "${vivid_pool_caps_output_dir}" PARENT_SCOPE)
    target_include_directories(${target_name} PRIVATE
        "${_VIVID_CMAKE_DIR}/core"
        "${vivid_pool_caps_output_dir}")

    if (CHARM_VIVID_FEATURESET STREQUAL "MCU_MIN")
        list(FILTER ${module_list_var} EXCLUDE REGEX "/Modules/ui/vivid/widgets/")
    endif()
    if (CHARM_VIVID_FEATURESET STREQUAL "MCU_MIN")
        list(REMOVE_ITEM ${module_list_var}
            "${PROJECT_SOURCE_DIR}/Modules/ui/vivid/core/object.cppm"
            "${PROJECT_SOURCE_DIR}/Modules/ui/vivid/core/input_interaction.cppm"
            "${PROJECT_SOURCE_DIR}/Modules/ui/vivid/core/string.cppm"
            "${PROJECT_SOURCE_DIR}/Modules/ui/vivid/core/virtual_list.cppm"
        )
    endif()

    set(${module_list_var} "${${module_list_var}}" PARENT_SCOPE)
endfunction()
