set(PLAYER_PROFILE_SOURCE "")
set(PLAYER_PROFILE_IMPL_SOURCES "")
set(PLAYER_PROFILE_MODULE_GROUPS "")

if (PLAYER_PROFILE STREQUAL "LEGACY_MAIN")
    set(PLAYER_PROFILE_SOURCE app/main.cpp)
    set(PLAYER_PROFILE_MODULE_GROUPS
        MODULE_GROUP_BASE
        MODULE_GROUP_PRODUCT_FS
        MODULE_GROUP_PRODUCT_AUDIO
        MODULE_GROUP_PRODUCT_DISPLAY
        MODULE_GROUP_PRODUCT_PLAYER_UI
        MODULE_GROUP_PRODUCT_LEGACY_RUNTIME)
elseif (PLAYER_PROFILE STREQUAL "USB_AS")
    set(PLAYER_PROFILE_SOURCE app/main-usb-as.cpp)
    set(PLAYER_PROFILE_IMPL_SOURCES
        "${CMAKE_CURRENT_SOURCE_DIR}/../../profiles/hqzy_cm7_usb_as.cpp")
    set(PLAYER_PROFILE_MODULE_GROUPS
        MODULE_GROUP_BASE
        MODULE_GROUP_PRODUCT_FS
        MODULE_GROUP_USB_STORAGE_RUNTIME)
elseif (PLAYER_PROFILE STREQUAL "USB_AUDIO")
    set(PLAYER_PROFILE_SOURCE app/main-usb-audio.cpp)
    set(PLAYER_PROFILE_IMPL_SOURCES
        "${CMAKE_CURRENT_SOURCE_DIR}/../../profiles/hqzy_cm7_usb_audio.cpp")
elseif (PLAYER_PROFILE STREQUAL "USB_SELF_MSC")
    set(PLAYER_PROFILE_SOURCE app/main-usb-self-msc.cpp)
    set(PLAYER_PROFILE_MODULE_GROUPS
        MODULE_GROUP_PRODUCT_BUNDLES
        MODULE_GROUP_PRODUCT_PROFILES
        MODULE_GROUP_HQZY_CM7_RUNTIME
        MODULE_GROUP_PRODUCT_PROFILE_SYSTEM)
elseif (PLAYER_PROFILE STREQUAL "USB_STORAGE")
    set(PLAYER_PROFILE_SOURCE app/main-usb-storage.cpp)
    set(PLAYER_PROFILE_IMPL_SOURCES
        "${CMAKE_CURRENT_SOURCE_DIR}/../../profiles/hqzy_cm7_usb_storage.cpp")
    set(PLAYER_PROFILE_MODULE_GROUPS
        MODULE_GROUP_PRODUCT_BUNDLES
        MODULE_GROUP_STORAGE_BOARD_MIN
        MODULE_GROUP_PRODUCT_FS
        MODULE_GROUP_USB_STORAGE_RUNTIME)
else()
    message(FATAL_ERROR "Unsupported PLAYER_PROFILE: ${PLAYER_PROFILE}")
endif()
