set(PLAYER_PROFILE_SOURCE "")
set(PLAYER_PROFILE_IMPL_SOURCES "")
set(PLAYER_PROFILE_MODULE_GROUPS "")
set(PLAYER_PROFILE_COMPILE_DEFINITIONS "")

if (PLAYER_PROFILE STREQUAL "LEGACY_MAIN")
    set(PLAYER_PROFILE_SOURCE app/main.cpp)
    set(PLAYER_PROFILE_MODULE_GROUPS
        MODULE_GROUP_PRODUCT_CONFIG
        MODULE_GROUP_BASE
        MODULE_GROUP_PRODUCT_FS
        MODULE_GROUP_PRODUCT_AUDIO
        MODULE_GROUP_PRODUCT_DISPLAY
        MODULE_GROUP_PRODUCT_PLAYER_UI
        MODULE_GROUP_PRODUCT_LEGACY_RUNTIME)
elseif (PLAYER_PROFILE STREQUAL "USB_AS")
    set(PLAYER_PROFILE_SOURCE app/main-usb-as.cpp)
    set(PLAYER_PROFILE_IMPL_SOURCES
        "${CMAKE_CURRENT_SOURCE_DIR}/../../profiles/hqzy_cm7_usb_as.cpp")
    set(PLAYER_PROFILE_COMPILE_DEFINITIONS
        CHARM_USBD_USE_COMPOSITE=1)
    set(PLAYER_PROFILE_MODULE_GROUPS
        MODULE_GROUP_PRODUCT_CONFIG
        MODULE_GROUP_BASE
        MODULE_GROUP_PRODUCT_FS
        MODULE_GROUP_USB_STORAGE_RUNTIME)
elseif (PLAYER_PROFILE STREQUAL "USB_AUDIO")
    set(PLAYER_PROFILE_SOURCE app/main-usb-audio.cpp)
    set(PLAYER_PROFILE_IMPL_SOURCES
        "${CMAKE_CURRENT_SOURCE_DIR}/../../profiles/hqzy_cm7_usb_audio.cpp")
    set(PLAYER_PROFILE_COMPILE_DEFINITIONS
        CHARM_USBD_USE_COMPOSITE=0)
    set(PLAYER_PROFILE_MODULE_GROUPS
        MODULE_GROUP_PRODUCT_CONFIG)
elseif (PLAYER_PROFILE STREQUAL "USB_SELF_CDC")
    set(PLAYER_PROFILE_SOURCE app/main-usb-self-cdc.cpp)
    set(PLAYER_PROFILE_MODULE_GROUPS
        MODULE_GROUP_PRODUCT_CONFIG
        MODULE_GROUP_BASE)
elseif (PLAYER_PROFILE STREQUAL "USB_SELF_MSC")
    set(PLAYER_PROFILE_SOURCE app/main-usb-self-msc.cpp)
    set(PLAYER_PROFILE_MODULE_GROUPS
        MODULE_GROUP_PRODUCT_CONFIG
        MODULE_GROUP_BASE
        MODULE_GROUP_PRODUCT_FS)
elseif (PLAYER_PROFILE STREQUAL "USB_STORAGE")
    set(PLAYER_PROFILE_SOURCE app/main-usb-storage.cpp)
    set(PLAYER_PROFILE_COMPILE_DEFINITIONS
        CHARM_USBD_USE_COMPOSITE=0)
    set(PLAYER_PROFILE_MODULE_GROUPS
        MODULE_GROUP_PRODUCT_CONFIG
        MODULE_GROUP_STORAGE_BOARD_MIN
        MODULE_GROUP_PRODUCT_FS
        MODULE_GROUP_USB_STORAGE_RUNTIME)
else()
    message(FATAL_ERROR "Unsupported PLAYER_PROFILE: ${PLAYER_PROFILE}")
endif()
