macro(player_cache_default name type default_value doc)
    if (NOT DEFINED ${name})
        set(${name} "${default_value}" CACHE ${type} "${doc}")
    endif()
endmacro()

function(player_bool_literal out_var value)
    if (${value})
        set(${out_var} 1 PARENT_SCOPE)
    else()
        set(${out_var} 0 PARENT_SCOPE)
    endif()
endfunction()

set(PLAYER_APP_PROFILE_ENUM "usb_self_msc")
if (PLAYER_PROFILE STREQUAL "LEGACY_MAIN")
    set(PLAYER_APP_PROFILE_ENUM "legacy_main")
elseif (PLAYER_PROFILE STREQUAL "USB_AS")
    set(PLAYER_APP_PROFILE_ENUM "usb_as")
elseif (PLAYER_PROFILE STREQUAL "USB_AUDIO")
    set(PLAYER_APP_PROFILE_ENUM "usb_audio")
elseif (PLAYER_PROFILE STREQUAL "USB_SELF_CDC")
    set(PLAYER_APP_PROFILE_ENUM "usb_self_cdc")
elseif (PLAYER_PROFILE STREQUAL "USB_SELF_MSC")
    set(PLAYER_APP_PROFILE_ENUM "usb_self_msc")
elseif (PLAYER_PROFILE STREQUAL "USB_STORAGE")
    set(PLAYER_APP_PROFILE_ENUM "usb_storage")
else()
    message(FATAL_ERROR "Unsupported PLAYER_PROFILE for config module: ${PLAYER_PROFILE}")
endif()

set(_player_usb_use_composite_default OFF)
if (PLAYER_PROFILE STREQUAL "USB_AS")
    set(_player_usb_use_composite_default ON)
endif()

player_cache_default(PLAYER_APP_RX_CAP STRING 64 "Player app USART RX ring capacity")
player_cache_default(PLAYER_APP_TX_CAP STRING 640 "Player app USART TX ring capacity")
player_cache_default(PLAYER_APP_BRINGUP_KEY_SELECT BOOL ON "Enable key-select during bringup")
player_cache_default(PLAYER_APP_BRINGUP_WAIT_KEY BOOL ON "Wait for key input during bringup")
player_cache_default(PLAYER_APP_ENABLE_AUDIO BOOL ON "Enable player audio path")
player_cache_default(PLAYER_APP_ENABLE_SDMMC_INIT BOOL OFF "Enable SDMMC init during app bringup")
player_cache_default(PLAYER_APP_ENABLE_USB_MSC BOOL ON "Enable USB MSC service")
player_cache_default(PLAYER_APP_USE_ST_USB_STACK BOOL ON "Use STM32 USB device stack")
player_cache_default(PLAYER_APP_ENABLE_USB_AUDIO BOOL ON "Enable USB audio service")
player_cache_default(PLAYER_APP_USE_USB_AUDIO_ON_BOOT BOOL ON "Enable USB audio on boot")
player_cache_default(PLAYER_APP_ENABLE_DISPLAY BOOL OFF "Enable display service")
player_cache_default(PLAYER_APP_USE_OUT_LOGGER_EARLY BOOL OFF "Enable early out logger")
player_cache_default(PLAYER_APP_USE_DMA_CONSOLE BOOL OFF "Enable DMA-backed console")
player_cache_default(PLAYER_APP_FMC_INIT_ON_BOOT BOOL ON "Run FMC init on boot")
player_cache_default(PLAYER_APP_SDRAM_SELFTEST_ON_BOOT BOOL ON "Run SDRAM self-test on boot")
player_cache_default(PLAYER_APP_SDRAM_SELFTEST_IN_BRINGUP BOOL OFF "Run SDRAM self-test in bringup")
player_cache_default(PLAYER_APP_ENABLE_I2S_INIT BOOL ON "Enable I2S init in app bringup")
player_cache_default(PLAYER_APP_ENABLE_SPI5_INIT BOOL ON "Enable SPI5 init in app bringup")
player_cache_default(PLAYER_APP_DEBUG_STOP_AFTER_BRINGUP BOOL OFF "Stop after bringup for debug")
player_cache_default(PLAYER_APP_DEBUG_STOP_AFTER_CHANNEL BOOL OFF "Stop after channel init for debug")
player_cache_default(PLAYER_APP_DEBUG_STOP_AFTER_FS BOOL OFF "Stop after FS init for debug")
player_cache_default(PLAYER_APP_DEBUG_DUMP_ROOT BOOL OFF "Dump root directory for debug")
player_cache_default(PLAYER_APP_ENCODER_TEST_ON_BOOT BOOL OFF "Run encoder test on boot")
player_cache_default(PLAYER_APP_ENCODER_TEST_MS STRING 5000 "Encoder test duration in milliseconds")
player_cache_default(PLAYER_APP_USB_USE_COMPOSITE BOOL ${_player_usb_use_composite_default} "Mirror the build-side USB composite selection into typed app config")

player_bool_literal(PLAYER_APP_BRINGUP_KEY_SELECT ${PLAYER_APP_BRINGUP_KEY_SELECT})
player_bool_literal(PLAYER_APP_BRINGUP_WAIT_KEY ${PLAYER_APP_BRINGUP_WAIT_KEY})
player_bool_literal(PLAYER_APP_ENABLE_AUDIO ${PLAYER_APP_ENABLE_AUDIO})
player_bool_literal(PLAYER_APP_ENABLE_SDMMC_INIT ${PLAYER_APP_ENABLE_SDMMC_INIT})
player_bool_literal(PLAYER_APP_ENABLE_USB_MSC ${PLAYER_APP_ENABLE_USB_MSC})
player_bool_literal(PLAYER_APP_USE_ST_USB_STACK ${PLAYER_APP_USE_ST_USB_STACK})
player_bool_literal(PLAYER_APP_ENABLE_USB_AUDIO ${PLAYER_APP_ENABLE_USB_AUDIO})
player_bool_literal(PLAYER_APP_USE_USB_AUDIO_ON_BOOT ${PLAYER_APP_USE_USB_AUDIO_ON_BOOT})
player_bool_literal(PLAYER_APP_ENABLE_DISPLAY ${PLAYER_APP_ENABLE_DISPLAY})
player_bool_literal(PLAYER_APP_USE_OUT_LOGGER_EARLY ${PLAYER_APP_USE_OUT_LOGGER_EARLY})
player_bool_literal(PLAYER_APP_USE_DMA_CONSOLE ${PLAYER_APP_USE_DMA_CONSOLE})
player_bool_literal(PLAYER_APP_FMC_INIT_ON_BOOT ${PLAYER_APP_FMC_INIT_ON_BOOT})
player_bool_literal(PLAYER_APP_SDRAM_SELFTEST_ON_BOOT ${PLAYER_APP_SDRAM_SELFTEST_ON_BOOT})
player_bool_literal(PLAYER_APP_SDRAM_SELFTEST_IN_BRINGUP ${PLAYER_APP_SDRAM_SELFTEST_IN_BRINGUP})
player_bool_literal(PLAYER_APP_ENABLE_I2S_INIT ${PLAYER_APP_ENABLE_I2S_INIT})
player_bool_literal(PLAYER_APP_ENABLE_SPI5_INIT ${PLAYER_APP_ENABLE_SPI5_INIT})
player_bool_literal(PLAYER_APP_DEBUG_STOP_AFTER_BRINGUP ${PLAYER_APP_DEBUG_STOP_AFTER_BRINGUP})
player_bool_literal(PLAYER_APP_DEBUG_STOP_AFTER_CHANNEL ${PLAYER_APP_DEBUG_STOP_AFTER_CHANNEL})
player_bool_literal(PLAYER_APP_DEBUG_STOP_AFTER_FS ${PLAYER_APP_DEBUG_STOP_AFTER_FS})
player_bool_literal(PLAYER_APP_DEBUG_DUMP_ROOT ${PLAYER_APP_DEBUG_DUMP_ROOT})
player_bool_literal(PLAYER_APP_ENCODER_TEST_ON_BOOT ${PLAYER_APP_ENCODER_TEST_ON_BOOT})
player_bool_literal(PLAYER_APP_USB_USE_COMPOSITE ${PLAYER_APP_USB_USE_COMPOSITE})

set(PLAYER_BOARD_SDMMC_CARD_ENUM "mmc")
player_cache_default(PLAYER_BOARD_SDRAM_BASE STRING 0xD0000000u "Player board SDRAM base address")
player_cache_default(PLAYER_BOARD_SDRAM_TEST_WORDS STRING 1024u "Player board SDRAM self-test word count")
player_cache_default(PLAYER_BOARD_SDRAM_TEST_PATTERN STRING 0xA5A50000u "Player board SDRAM self-test pattern")
player_cache_default(PLAYER_BOARD_SDRAM_REFRESH_RATE STRING 0x0603u "Player board SDRAM refresh rate")
player_cache_default(PLAYER_BOARD_SDMMC_CARD STRING MMC "Player board SDMMC card kind")
set_property(CACHE PLAYER_BOARD_SDMMC_CARD PROPERTY STRINGS MMC SD)
player_cache_default(PLAYER_BOARD_SDMMC_INIT_CLOCK_DIV STRING 480u "Player board SDMMC init clock divider")
player_cache_default(PLAYER_BOARD_SDMMC_XFER_CLOCK_DIV STRING 4u "Player board SDMMC transfer clock divider")
player_cache_default(PLAYER_BOARD_SDMMC_BUS_WIDTH STRING 4u "Player board SDMMC bus width")
player_cache_default(PLAYER_BOARD_SDMMC_USE_DMA BOOL OFF "Player board SDMMC DMA usage")
player_cache_default(PLAYER_BOARD_SDMMC_TRY_4BIT BOOL OFF "Player board SDMMC try 4-bit mode")
player_cache_default(PLAYER_BOARD_SDMMC_PROBE_READ BOOL OFF "Player board SDMMC probe-read after init")
player_cache_default(PLAYER_BOARD_SDMMC_VERBOSE BOOL OFF "Player board SDMMC verbose logging")
player_cache_default(PLAYER_BOARD_SDMMC_VERBOSE_GPIO BOOL OFF "Player board SDMMC verbose GPIO logging")
player_cache_default(PLAYER_BOARD_SDMMC_PARTITION_LBA STRING 496u "Player board SDMMC partition LBA")
player_cache_default(PLAYER_BOARD_KEY_ACTIVE_HIGH BOOL ON "Player board key active-high polarity")

if (PLAYER_BOARD_SDMMC_CARD STREQUAL "MMC")
    set(PLAYER_BOARD_SDMMC_CARD_ENUM "mmc")
elseif (PLAYER_BOARD_SDMMC_CARD STREQUAL "SD")
    set(PLAYER_BOARD_SDMMC_CARD_ENUM "sd")
else()
    message(FATAL_ERROR "Unsupported PLAYER_BOARD_SDMMC_CARD: ${PLAYER_BOARD_SDMMC_CARD}")
endif()

player_bool_literal(PLAYER_BOARD_SDMMC_USE_DMA ${PLAYER_BOARD_SDMMC_USE_DMA})
player_bool_literal(PLAYER_BOARD_SDMMC_TRY_4BIT ${PLAYER_BOARD_SDMMC_TRY_4BIT})
player_bool_literal(PLAYER_BOARD_SDMMC_PROBE_READ ${PLAYER_BOARD_SDMMC_PROBE_READ})
player_bool_literal(PLAYER_BOARD_SDMMC_VERBOSE ${PLAYER_BOARD_SDMMC_VERBOSE})
player_bool_literal(PLAYER_BOARD_SDMMC_VERBOSE_GPIO ${PLAYER_BOARD_SDMMC_VERBOSE_GPIO})
player_bool_literal(PLAYER_BOARD_KEY_ACTIVE_HIGH ${PLAYER_BOARD_KEY_ACTIVE_HIGH})

set(PLAYER_GENERATED_MODULE_DIR "${CMAKE_CURRENT_BINARY_DIR}/generated/player")
file(MAKE_DIRECTORY "${PLAYER_GENERATED_MODULE_DIR}")

set(PLAYER_APP_CONFIG_GENERATED_CPPM
    "${PLAYER_GENERATED_MODULE_DIR}/player_app_config.generated.cppm")
set(PLAYER_BOARD_CONFIG_GENERATED_CPPM
    "${PLAYER_GENERATED_MODULE_DIR}/player_board_config.generated.cppm")
configure_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/player_app_config.generated.cppm.in"
    "${PLAYER_APP_CONFIG_GENERATED_CPPM}"
    @ONLY)
configure_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/player_board_config.generated.cppm.in"
    "${PLAYER_BOARD_CONFIG_GENERATED_CPPM}"
    @ONLY)

set(PLAYER_GENERATED_MODULES
    "${PLAYER_APP_CONFIG_GENERATED_CPPM}"
    "${PLAYER_BOARD_CONFIG_GENERATED_CPPM}")
