if (NOT DEFINED CHARM_FREETYPE_DIR OR CHARM_FREETYPE_DIR STREQUAL "")
    set(CHARM_FREETYPE_DIR "${CMAKE_CURRENT_LIST_DIR}/../Modules/thirdparty/freetype"
        CACHE PATH "Path to the FreeType source tree")
else()
    set(CHARM_FREETYPE_DIR "${CHARM_FREETYPE_DIR}"
        CACHE PATH "Path to the FreeType source tree" FORCE)
endif()

function(charm_link_freetype target_name)
    if (TARGET freetype)
        target_link_libraries(${target_name} PRIVATE freetype)
        target_include_directories(${target_name} PRIVATE ${CHARM_FREETYPE_DIR}/include)
        target_compile_definitions(${target_name} PRIVATE CHARM_ENABLE_FREETYPE=1)
        return()
    endif()

    if (EXISTS "${CHARM_FREETYPE_DIR}/CMakeLists.txt")
        set(FT_DISABLE_ZLIB ON CACHE BOOL "" FORCE)
        set(FT_DISABLE_BZIP2 ON CACHE BOOL "" FORCE)
        set(FT_DISABLE_PNG ON CACHE BOOL "" FORCE)
        set(FT_DISABLE_HARFBUZZ ON CACHE BOOL "" FORCE)
        set(FT_DISABLE_BROTLI ON CACHE BOOL "" FORCE)
        add_subdirectory(${CHARM_FREETYPE_DIR} ${CMAKE_BINARY_DIR}/freetype)
        target_compile_definitions(freetype PRIVATE CHARM_LIB_BUILD=1)
        target_link_libraries(${target_name} PRIVATE freetype)
        target_include_directories(${target_name} PRIVATE ${CHARM_FREETYPE_DIR}/include)
        target_compile_definitions(${target_name} PRIVATE CHARM_ENABLE_FREETYPE=1)
    else()
        message(WARNING "FreeType requested but not found under ${CHARM_FREETYPE_DIR}")
    endif()
endfunction()
