function(charm_enforce_no_shared_libs)
    if (BUILD_SHARED_LIBS)
        message(FATAL_ERROR "BUILD_SHARED_LIBS=ON is forbidden for this project")
    endif()

    get_property(all_targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
    foreach(tgt IN LISTS all_targets)
        get_target_property(tgt_type ${tgt} TYPE)
        if (tgt_type STREQUAL "SHARED_LIBRARY" OR tgt_type STREQUAL "MODULE_LIBRARY")
            message(FATAL_ERROR "Shared library target is forbidden: ${tgt}")
        endif()
    endforeach()
endfunction()
